### ISSUE TITLE
Endpoint pour  la liste des clubs

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#1]
Fournir un endpoint pour la liste des clubs avec toutes les informations de chaque club:
  - nom
  - id
  - contact
  - geolocalisation
  - description
  - logo
  - image de fond
  - facebook
  - ...

**Comment by Lo0ping** [comment]
http://api.volley34.fr/api/clubs

**Comment by Lo0ping** [comment]
> http://api.volley34.fr/api/clubs
ATTENTION
@eric-taix, je change l'url, c'est désormais : http://api.volley34.fr/v1/clubs
