### ISSUE TITLE
Afficher les clubs favoris sur le dashboard

### ISSUE THREAD

**Issue by eric-taix-teads** [eric-taix/volley34-mobile#10]

**Comment by Lo0ping** [comment]
est ce utile d'avoir plusieurs club favoris ?
perso, je limiterai a un seul

**Comment by eric-taix** [comment]
Je suis d'accord, il y a à priori peu d'intérêt. Après cela ne me coute rien et permet à celui qui fait partie de plusieurs clubs de les sélectionner ! Après c'est facile à enlever si tu penses qu'il n'y a pas d'intérêt.
 
La question se pose aussi un peu pour les équipes:
  - Est ce que les équipes favorites sont toutes les équipes du club favori ?
  - Ou est ce que lorsque l'on sélectionne le 1er club favori alors toutes les équipes sont sélectionnées comme favorites par défaut avec possibilité de déselectionner les équipes favorites
  - Ou un sélectionne son club favori et après on doit sélectionner les équipes favorites une par une

Perso je partais pour la solution 2: un club favori et automatiquement toutes les équipes du club deviennent favorites avec possibilité de les déselectionner si besoin car je pense que cela correspond à la majorité des clubs ou les adhérents sont intéressés par les autres équipes car tout le monde se connait un peu.

Un avis ?

**Comment by eric-taix-teads** [comment]
Après avoir demander l'avis à un groupe d'utilisateur test (du club de Vailhauquès), il apparaît que plusieurs équipes favorites semblent être intéressant et aussi les clubs (même si j'ai beaucoup de doute sur plusieurs clubs).
Je ferme quitte à créer un autre ticket si besoin pour supprimer
