### ISSUE TITLE
Tabs are not displayed

### ISSUE THREAD

**Issue by eric-taix-teads** [eric-taix/volley34-mobile#102]
Tabs are not displayed on iOS (emulator iPhone 11 and probably others).
What's strange is that it is not displayed when a tab contains a body and still be displayed when the content of the tab is empty!
Note: And it's not a matter of theme (light or dark): I tried both themes

These pages do not display tabs:
![Simulator Screen Shot - iPhone 11 - 2020-08-18 at 15 45 27](https://user-images.githubusercontent.com/42940156/90520900-33cbd200-e16a-11ea-934f-5063313dcc40.png)
![Simulator Screen Shot - iPhone 11 - 2020-08-18 at 15 45 32](https://user-images.githubusercontent.com/42940156/90520908-36c6c280-e16a-11ea-99c1-ad9b7b3964a1.png)

This one displays tabs
![Simulator Screen Shot - iPhone 11 - 2020-08-18 at 15 45 38](https://user-images.githubusercontent.com/42940156/90520925-3b8b7680-e16a-11ea-8dd2-eec67184fac4.png)

**Comment by eric-taix** [comment]
Closed by #105
