### ISSUE TITLE
Use relevant informations to route to a gymnasium

### ISSUE THREAD

**Issue by eric-taix-teads** [eric-taix/volley34-mobile#104]
Instead of using the name to route the user to a gymnasium, we must concat the `Adresse`, `CP` and `Ville` fields.
Example: For `Gymnase Jean RAMEL` the field are:
```json
        "GymnaseCode": "MTP_RAMEL",
        "Nom": "Gymnase Jean RAMEL",
        "Adresse": "rue José-Maria De Hérédia",
        "CP": "34070",
        "Quartier": "Figuerolles",
        "Ville": "Montpellier",
        "Telephone": "04 67 27 49 14",
        "PlanAcces": "https://goo.gl/dbkGHB",
        "Terrains": 3,
        "GPS": "43.605578|3.856689",
        "NomComplet": "Gymnase Jean RAMEL (Montpellier Figuerolles)",
        "Created": null,
        "Modified": null,
        "Prefixe": "au",
        "TexteNomComplet": "au Gymnase Jean RAMEL (Montpellier Figuerolles)"
```
And the `Nom` field is used to route which is (almost) impossible, except for particular cases, for the maps application to find the point. If we use fields (see below) then it should find the point easily.

**Comment by thomasFoulon** [comment]
In fact I have used the `"GPS": "43.605578|3.856689"` information but it's true that this is not very clear for the user who will see this information on Google Maps for example instead of "Gymnase Jean Ramel, ...".

**Comment by eric-taix** [comment]
The route seems ok so let's close it for now
