### ISSUE TITLE
Only one favorite team

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#113]
**Rationale**

I had a good discussion with a senior UX designer yesterday night. She loves the design of the application, but she also told me that we've made a big mistake !

We were trying to create the application for multiple end-users (players, captains, club president and more) which seems fine but we lost the fact that 90% of our users are players. She told me that the first screen (dashboard) should **only** display the useful informations for a player (other end-users may have access to other informations by navigating deeper into the application or in the bottom menu). What does it means ?

**Implementation**

1- It means that it must has one and only one favorite team. This favorite team should be part of the end-user's profile (see also #94). 
2- The favorite widget must be remove everywhere (club and team)
3- The labels in the dashboard must be `Votre club`, `Votre équipe`, `Votre agenda`
4- The favorite club is the club of the favorite team (no user selection)
5- When the application starts, if there's no favorite team, then display a dialog to select a club, then display teams of that club
6- The user can close this dialog until he has selected a team
7- This selection may be change later in the profile's menu
8- If the user want to change the favorite team, then the previous favorite team is unselected

This is a big change, but not so big. Let's implement it asap.

**Comment by Lo0ping** [comment]
Hi,
Not agree with this !
We can just have 1 favorite club but you **must** keep multiple favorite teams capability.
I one of my app function requirement

**Comment by Lo0ping** [comment]
Anyway, I still agréé with change to manage those informations in user profile menu

**Comment by thomasFoulon** [comment]
Do we have to keep the dashboard like it is, with a card for the club, a card for the team and then a the agenda ? Or it has to change completely to look like the team page details ?

**Comment by eric-taix-teads** [comment]
What do you mean with "like the team page details" ?

Not sure to understand your comment, but cards are (for now) explicit widgets that are clickable. And if we want to let the user being able to click on his club or team (no matter the number of clubs / teams) to open details, we have to keep the card widget no?

**Comment by thomasFoulon** [comment]
Yes, my question was do we have to change the dashboard presentation according to this change.

**Comment by eric-taix** [comment]
So no I don't think so

Le mer. 26 août 2020 à 16:25, thomasFoulon <notifications@github.com> a
écrit :

**Comment by eric-taix** [comment]
Done
