### ISSUE TITLE
[team details] Add an agenda tab

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#116]
In the team's details page we must add a tab which display this team's agenda (match + tournament + meeting).
This agenda should not only display the first 3 weeks but should display all the season events. If the loading time to load the full agenda is too long, then we must implement a infinite list - load next weeks when the user scrolls.

**Comment by thomasFoulon** [comment]
@Lo0ping For the infinite list, is the parameter `min` and `max` is implemented for matches on the API? I think that's not the case... Example: http://api.volley34.fr/v1/equipes/AVGM1/matchs?min=2020-09-08T20:15:00

**Comment by eric-taix** [comment]
Seems to be implemented
