### ISSUE TITLE
[gymnasium] Page UI

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#119]
I'm implementing the gymnasium page and at first I thought to add tabs into the club page.

My goal was to be able to browse clubs while seeing the gymnasiums where clubs are playing (a bit like Google maps application when you search for a restaurant: in the bottom you have a pageview which displays one club at a time and when you "select" - by swiping - another club then the markers which represent the gymnasium of the current selected club are displayed or highlighted)

Another solution is to add a new tab at the bottom of the main page (right to the club tab) which displays a page specific to gymnasiums (same UI but does not display clubs in the pageview but gymnasiums)

Each solution is for a different usage, and I'm not sure of the use case we want to implement and why.

The first is to display gymnasiums where a club play (but difficult/impossible to display the day and hours of each gymnasium because a club may have multiple gymnasiums)

The second is to display each gymnasium individually: day and hours can be displayed. But how to display club if multiple clubs use the same gymnasium ?

My current thought is to implement the second solution also because top tabs while also having bottom tabs is not a good pattern of navigation.

Any thoughts ? @Lo0ping , @thomasFoulon ?

**Comment by eric-taix-teads** [comment]
As no comment has been added, I decided to implement the 2nd solution because:  
  - It mimics the current web site  
  - Implementing a tab in the clubs page was a pain. 
  - bottom + top tabs should be used with caution  (see https://material.io/components/bottom-navigation#usage)

The gymnasiums map has been implemented by #133
