### ISSUE TITLE
Affichage des logos clubs

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#12]
Hello, 

serait il possible de redimensionner les logos dans les pastilles et de le mettre sur fond blanc ?

**Comment by eric-taix-teads** [comment]
> Hello,
> 
> serait il possible de redimensionner les logos dans les pastilles et de le mettre sur fond blanc ?

Oui tout est possible 😄 
Mes réflexions sur sur ce sujet:  
  - La taille du logo doit être proportionné aux informations sur l'on affiche afin de laisser le plus de place possible pour les informations qui sont plus importantes
  - Le logo sera affiché en beaucoup plus gros dans la fiche de détail d'un club
  - Je trouve que les pastilles avec un fond blanc attirent l'oeil et font perdre l'essentiel des infos car il y a un fort contraste entre les pastilles et les cards
  - J'avais prévu d'avoir 2 thèmes (dark et light) et avec possibilité de passer automatiquement de l'un à l'autre en fonction de la lumière du jour comme cela se fait sur les nouveaux téléphone quand les applications le permettent. Le thème actuel est le black. Je n'ai pas encore les idées claies sur le thème light mais il tournera certainement avec du blanc et donc les pastilles blanches aussi dans mon idée.

Je viens de te faire un exemple de ce que cela donnerait (logo qui passe de 40 à 50 - je n'ai pas fixé le problème des marges pour faire ce screenshot) histoire que l'on puisse se faire une idée de ta suggestion.
![Screenshot_20200422-121323](https://user-images.githubusercontent.com/42940156/79970232-e331ba00-8492-11ea-8253-c478e77e2c7e.jpg)

**Comment by Lo0ping** [comment]
En fait, je pensais a reduire la taille de l'image logo pour qu'il entre dans la pastille : 

![image](https://user-images.githubusercontent.com/3205330/79974689-0e6bd780-849a-11ea-990a-a8296c568975.png)

pour le fond blanc, en laissant la pastille a 40, je ne pense pas que ce ça soit agressif sur un thème sombre ... à vérifier.

sinon, je peux essayer de voir a faire des logos pour dark theme

**Comment by eric-taix-teads** [comment]
ok pardon, je viens de corriger pour avoir les logos qui s'affichent en entier dans la pastille. Je ferais un test avec les pastilles blanches ce soir en 40 et je te dis çà

**Comment by eric-taix-teads** [comment]
Ok le fond est en blanc et les logos rentrent dans la pastille
