### ISSUE TITLE
Format des URL de l'api

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#14]
l'URL `http://api.volley34.fr/v1/Equipes/Club/{{Club}}` ne donnent pas la hiérarchie des entités que l'on récupère

Du coup en voyant l'api j'aurais plutôt vu : 
  -  `http://api.volley34.fr/v1/clubs/`
  -  `http://api.volley34.fr/v1/clubs/{{club}}`
  -  `http://api.volley34.fr/v1/clubs/{{club}}/equipes`
  -  `http://api.volley34.fr/v1/clubs/{{club}}/equipes/{{equipe}}`
  -  `http://api.volley34.fr/v1/clubs/{{club}}/equipes/{{equipe}}`
  -  `http://api.volley34.fr/v1/clubs/{{club}}/creneaux`
  -  `http://api.volley34.fr/v1/equipes`
  -  `http://api.volley34.fr/v1/equipes/{{equipe}}`
  -  `http://api.volley34.fr/v1/equipes/{{equipe}}/matchs`
  -  `http://api.volley34.fr/v1/equipes/{{equipe}}/matchs?filter=next`
  -  `http://api.volley34.fr/v1/equipes/{{equipe}}/resultats`
  -  `http://api.volley34.fr/v1/equipes/{{equipe}}/resultats/{{match}}`
  -  `http://api.volley34.fr/v1/classements/{{saison}}`
  -  `http://api.volley34.fr/v1/classements/{{saison}}/{{competition}}`
  -  `http://api.volley34.fr/v1/classements/{{saison}}/{{competition}}/{{division}}`
  -  `http://api.volley34.fr/v1/classements/{{saison}}/{{competition}}/{{division}}/{{poule}}`
  -  `http://api.volley34.fr/v1/resultats/{{saison}}`
  -  `http://api.volley34.fr/v1/resultats/{{saison}}/{{competition}}`
  -  `http://api.volley34.fr/v1/resultats/{{saison}}/{{competition}}/{{division}}`
  -  `http://api.volley34.fr/v1/resultats/{{saison}}/{{competition}}/{{division}}/{{poule}}`

C'est peut être un peu du détail et je ne me rends pas compte la charge de travail pour faire ces changement mais l'idée est d'avoir une api un peu plus REST:
  1- minuscule dans les URLs
  2- pluriel sur le nom des ressources 
  3- un ID/CODE à la suite d'une ressource pour accéder à une ressource en particulier d'une liste
  4- ressources hiérarchiques

Ce ticket est une discussion pour voir ce que tu en penses ?
PS: certaines URL ne sont pas remplis sur PostMan (Match information, Match par équipe par exemple) et il manque un endpoint pour les autres RDV (tournois, réunion, ...)

**Comment by Lo0ping** [comment]
Salut, 

ça me va :)

juste un détail, pour moi l'application ne prend en compte que la saison en cours.
du coup, pour classements et resultats, je retire /{{saison}}

pour le calendrier, je n'ai pas encore fait le endpoint, donc, normal qu'il manque ;)

Enfin, je regarde pour mettre a jour postman.

**Comment by eric-taix** [comment]
Comment peut-on extraire d'une équipe, dans quel championnats elle joue ?
par exemple savoir qu'elle joue en 4x4 mixte par exemple en poule excellence.

**Comment by Lo0ping** [comment]
Normalement, c'est bon...

**Comment by Lo0ping** [comment]
> Comment peut-on extraire d'une équipe, dans quel championnats elle joue ?
je peux ajouter 
http://api.volley34.fr/v1/equipes/{{Equipe}}/competitions
