### ISSUE TITLE
APIs whishlist

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#140]
Here are the list of expected improvements / new apis endpoint. This issue is mainly to discuss about each points. When accepted by everyone, I suggest to create a specific issue per improvement / new apis, so we'll be able to track them individually.  

__Please note that this issue will be filled as things progress__

  

1. Match results per Competition / Division / Group. Examples: all results for the "Championnat 4x4 mixte / Excellence" or all results for the "Championnat 4x4 mixte / Excellence / Poule 2".  
  Motivation: It aims to compute some interesting statistics per Division or Division / Group like "Attack Force" or "Defense Potential" (note that this kind of filtering - ie Division or Group - already exist for the ranking api but not for the results)
  
 2. `Division` & `Poule` do not seem to be filled in the team informations endpoint (http://api.volley34.fr/v1/equipes/{{Equipe}}). Tried with `VCVX1`, `VCVX2` and `VCVX6` and the `Division` & `Poule` attributs are always 0 
  
 3. :rocket: Team information endpoint (http://api.volley34.fr/v1/equipes/{{Equipe}}) is slow (3,6 seconds)
  
 4. :rocket: The endpoint "http://api.volley34.fr/v1/equipes/{{Equipe}}/resultats" to retrieve result per team is slow: 3,36s on average for 3 matches. is there a missing index in the database for the results or is it possible to improve it?
  
Note: To mitigate latency issues, we've set up a HTTP cache, which is the worst idea we've never had! Caches are always difficult to manage and datas can diverge from one screen to other depending on the  current request state. I think I'll remove this cache but then the application will be very slow.

**Comment by Lo0ping** [comment]
1. Done. ex : http://api.volley34.fr/v1/resultats/2022-C001/1/1
2. Done
3. Can you check, it would be better ...
4. see 3.

Season Index have been added everywhere et datacontext elements loaded when necessary

**Comment by eric-taix** [comment]
1- It works
2- All attributs are now filled
3- Latency is now 86ms which is a big improvement !
4- Latency is now 234ms which is also a big improvement !

You rocks @Lo0ping  👍  Thanks you so much for this quick improvements

**Comment by eric-taix** [comment]
I've probably made a mistake when asking to fill `Division` & `Poule` when requesting a team's informations: These attributes are related to a specific competition as a team can be registered in multiple competition no? Otherwise I missed something....

If this is true then it means that these attributes must not be returned when requesting team's informations BUT must be returned when asking for registered competition for a team (i.e. http://api.volley34.fr/v1/equipes/{{Equipe}}/competitions)

**Comment by Lo0ping** [comment]
done

**Comment by eric-taix** [comment]
Close for now. I'll open a new issue in case
