### ISSUE TITLE
In match details add the ability to display the opponents details

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#146]

**Comment by Lo0ping** [comment]
Which details ?

**Comment by eric-taix** [comment]
Some people ask me to be able to open the detailed page of the opponent to see some statistics instead of having to go the clubs page, search for the club then search for the team and then open it.

I'm not sure this is the right place to open details (i.e. in match details). I have already provide this kind of shortcut in the ranking table (see the video) which is perhaps enough.

https://user-images.githubusercontent.com/712517/144468543-da5669ee-c1c6-4f4b-848a-96179bc1a32a.mp4

**Comment by Lo0ping** [comment]
why not
