### ISSUE TITLE
[match details] Let the user download the match sheet (to be printed)

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#147]

**Comment by matt-aubert** [comment]
The match sheet only appears when we display the game from the dashboard.
When we access the game from the "club" screen path : no match sheet (even for favorite team)

**Comment by eric-taix** [comment]
Just move it to Todo: this issue is not fixed. 

Good catch by the way: I've seen that sometimes the scoresheet was not available but I couldn't figure out why
