### ISSUE TITLE
Add the attack / defense forces in the dashboard agenda

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#152]
As implemented in a team agenda, display forces comparison between opponents.

**Comment by eric-taix** [comment]
@matt-aubert Didn't we say that this issue is reported to the next release?

**Comment by matt-aubert** [comment]
> @matt-aubert Didn't we say that this issue is reported to the next release?

yes that's correct, I push it to v2

**Comment by eric-taix** [comment]
Change to release v1 as already implemented in v1 with an option (default to false) to display it.
