### ISSUE TITLE
Endpoint pour le calendrier hors matchs

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#16]
http://api.volley34.fr/v1/calendars

**Comment by eric-taix** [comment]
Top 👍
Il y a un moyen sur ce endpoint de limiter le retour en donnant un nombre
max ou une date max ou donner 2 dates (min et Max) en paramètre de l'URL ?

**Comment by Lo0ping** [comment]
je mets dans le wiki la doc de l'API (postman bof) du coup, j'ai commencé par le calendrier qui manquait à postman : [https://github.com/eric-taix/volley34-mobile/wiki/API-Documentation](url)
