### ISSUE TITLE
No club to favorite : list of clubs not visible

### ISSUE THREAD

**Issue by kverbard** [eric-taix/volley34-mobile#168]
prerequisites : 
No Club added to favorites

1- Open the "Club" menu => The clubs are not viewable (cf. attachments) 

![image-168](https://user-images.githubusercontent.com/95641846/145547784-cfb0392c-be9d-4567-8371-96826eb6344f.jpg)

Edited for image size

**Comment by Lo0ping** [comment]
Internet issue

**Comment by eric-taix** [comment]
No @Lo0ping this issue was found before the internet issue. It seems that when the user has no favorite, something goes wrong in almost all screens (probably the favorite star at the upper right corner)

**Comment by matt-aubert** [comment]
solved by #171 no possibility to navigate without favorite club
