### ISSUE TITLE
Endpoint de stats par club

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#17]
Dans la dashboard, sur la card d'un club l'idée est d'afficher des mini stats:
<img width="349" alt="Capture d’écran 2020-04-26 à 11 31 14" src="https://user-images.githubusercontent.com/712517/80303596-85aead80-87b1-11ea-9955-85c22f9907f1.png">

Aujourd'hui pour implémenter ce besoin cela demande de nombreuses requêtes:
  1- info sur le club
  2- la liste des équipes du club
  3- les matchs joués par équipe (que je filtre pour ne récupérer que le dernier match)
  4- le calendrier par équipe (que je filtrer pour ne récupérer que le prochain)
Donc si dans un club tu as 6 équipes cela fait: 1 + 1 + 6 + 6 = 14 requêtes vers le serveur.

Je vais rajouter un cache dans mon client HTTP (6 heures / 12 heures ?) pour éviter de charger le serveur d'autant que les données ne changent pas très souvent.

Pour autant cela n'est pas une solution top ! Je vois 3 solutions:
  1- Ajouter un endpoint pour les clubs qui remonterait en plus des infos du club, les équipes (juste le code + le résultat du(es) derniers matchs + le(s) prochain(s) match(s) à venir)
  2- Ajouter un endpoint pour les clubs qui remonterait les statistiques que l'on souhaite voir sur le dashboard
  3- Monter un serveur GraphQL en front de l'API pour permettre aux clients de choisir les données qu'ils veulent

Les solutions 1 et 2 sont les plus rapides à monter mais la solution 3 est la plus pérenne car on pourra faire évoluer les besoins d'affichage des clients sans modification du serveur.

PS: Ce besoin de stat pour les club existe aussi pour les équipes avec des remontées de données différentes

**Comment by Lo0ping** [comment]
Quelles stats tu voudrais en fait ?
par club : ...
par equipe : ...
par saison ?

**Comment by eric-taix** [comment]
Stats est un grand mot et certainement mal employé ! En tout cas je ne pensais pas à des stats sportives complètes mais pour l'écran principal qui sert de dashboard, cela me semble important d'afficher des infos qui servent et dynamiques. On a bien sûr l'agenda de la semaine avec les matchs des équipes favorites, ainsi que les tournois, ...

Pour les clubs j'ai déjà fait les matchs gagnés / matchs joués de la semaine précédente (c'est une info sympa pour voir comment est la santé des matchs de toutes les équipes du club de façon général - pour les grands clubs avec plusieurs dizaines d'équipes c'est moins important).

Pour chaque équipe, je verrais bien un mini graphique sur l'évolution du nombre de points / match gagné depuis la saison, son classement (avec une info visuelle pour savoir si elle est reléguée/promue suivant le compétitions)

**Comment by Lo0ping** [comment]
Pour les équipe, j'ai fait ça : http://api.volley34.fr/v1/Equipes/{{Equipe}}/stats

je vais voir ce que je peux faire avec 
- [X] http://api.volley34.fr/v1/clubs/{{Club}}/stats
- [ ] http://api.volley34.fr/v1/competitions/{{competition}}/stats
- [ ] http://api.volley34.fr/v1/saison/stats

**Comment by eric-taix** [comment]
Génial, merci tu es plus rapide que Lucky Luke  🍾 
Juste si tu pouvais mettre des noms de champ plutôt que les libellés. 
Ex: `"Matchs à domicile"` -> `MatchsDomicile`

Pour les graphes des équipes que je voulais faire, je prendrais directement le résultats des matchs de l'équipe

**Comment by Lo0ping** [comment]
> Juste si tu pouvais mettre des noms de champ plutôt que les libellés.
> Ex: "Matchs à domicile" -> MatchsDomicile

j'ai hésiter a les nommer ainsi, je change ça

**Comment by Lo0ping** [comment]
j'ai modifié les nom 

et :
[X] http://api.volley34.fr/v1/clubs/{{Club}}/stats

**Comment by Lo0ping** [comment]
- http://api.volley34.fr/v1/competitions/{{competition}}/stats
- http://api.volley34.fr/v1/saison/stats
- http://api.volley34.fr/v1/saison/stats?typeCompetition=CH
