### ISSUE TITLE
Improve first Club/Team selection - first app launch

### ISSUE THREAD

**Issue by matt-aubert** [eric-taix/volley34-mobile#171]
This improvement also affects #159 for the navigation menu and #168 for display bug when no favorite.

When first launching the app, this is a little tricky to add the first club (6 actions doesn't fell very user friendly) :

1- Go to menu
2- Click on "edit" pencil
3- Select the club
4- Click on next
5- Select the team
6- Click save

What I see as an improvement would be : 

**1- First app launch :** 
> Display automatically the list of Clubs 
(since you can't use the app without having at least one club, it does not make sense to allow it)
Resolve issue #168 

**2- Select the club :** 
> Directly leads you to the team selection 
(the validation button would have been useful only if club multi selection was possible)

**3- Select the team :** 
> Leads to final home screen

No bottom navigation bar at all
Makes the navigation lighter and intuitive.
Get rid of the "Pencil" icon in the parameters menu.
Resolve issue #159 

To add another equip => You can use the "Equipe" tab of the club and add to favorite
To add another club => You can use the "Clubs" tab and add to favorite
No possibility to remove the only Club from favorite, you'd need to add another one first. Or, if possible, you would be back to **step 1**

**Comment by eric-taix** [comment]
I totally agree with you, this is too tricky today. But I would add a "Profil" menu item to:
 - let the user be able to change its club or its team (in the event of a miss)
 - start to build the profil page (see #94)

Otherwise everything is fine for me 👍

**Comment by matt-aubert** [comment]
Hi Eric,
We noticed yesterday that the selection of the club and team could be improved by removing the radio buttons at the left side and make the whole "line" clickable instead
Do you want me to reopen this issue or create a new one ?
Thanks

**Comment by eric-taix** [comment]
Reopen it, it's not solved 😉
