### ISSUE TITLE
Division & Pool id after the first phase

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#176]
@Lo0ping I'm wondering how the pools will be numbered after the current phase of the championship?

Explanation: today the vcv1 and vcv2 are in the same division (EX) but in different pools (1 & 2). After the first phase, these teams will probably stay in the division EX but what about the pool? Will it be 1 or 2 or a new pool number like 0 or a currently non existing pool number (4 for example)? I ask this question because I currently retrieve match results and compute some statistics from these results by requesting the division and pool results. If the pool number in the next phase uses an already existing pool number then I'll compute statistics with results from the first phase otherwise statistics will start from scratch on the second phase (which is probably better). If the pool number in the second phase uses and already existing pool number then some teams will have statistics and others not, according to their respective pool number in the first phase

**Comment by Lo0ping** [comment]
So ....
It will be like past year Division (=EX, HO, PR, ...) and pool number will be 0
**BUT**
CompetitionCode wil change 2022-C0**1**X instead of 2022-C00X

**Comment by eric-taix** [comment]
Ok seems to be fine even if I have to check.

Is there a way to detect if a competition is a "brassage" or not? Are pool number > 0 means "brassage" and pool number 0 means that it's not a "brassage"? As the competition will change, it means that we'll have two tabs (+ results + agenda) and 3 tabs with spring cup and 4 tabs if the team is also registered in the challenge.

I have to make a visual difference between the championship tabs and I can't really use `Libelle` attribut as it's too long (i.e. `Championnat 2022 - Brassage 4x4 Mixte`)

**Comment by eric-taix** [comment]
Not more relevant today
