### ISSUE TITLE
First favorite selection - back to club after team select

### ISSUE THREAD

**Issue by matt-aubert** [eric-taix/volley34-mobile#177]
When first selecting the favorite team : 

Current :
- Select Club > goes to team selection
- Select Team > goes back to club selection

expected : 
- Select Club > goes to team selection
- Select Team > goes to dashboar

I tried and verified that several times. (Android)

https://user-images.githubusercontent.com/95641846/146197489-3325a775-94e2-4d93-a52d-42815a6c84f9.mp4

**Comment by eric-taix** [comment]
I was able to reproduce it 👍

**Comment by eric-taix** [comment]
As a reminder, during the first launch the user should not be able to close the club and team selection.

**Comment by matt-aubert** [comment]
black screen after team selection

**Comment by eric-taix** [comment]
I can reproduce it with my mobile but unfortunately not with my emulator....
I'll try to understand what can happen without being able to repro

**Comment by matt-aubert** [comment]
@eric-taix 

I still noticed a little backward step before displaying the dashboard see the video

Tell me if you want to keep it that way for v1 or not, then I will sort this issue accordingly.

https://user-images.githubusercontent.com/95641846/148212163-50dfec5c-1b02-4520-8e90-594048aeff59.mp4

**Comment by eric-taix** [comment]
I think I wait for the favorite team to be saved before closing the page. Keep it in "todo", I'll check if it's easy or not to fix this.
