### ISSUE TITLE
A event is not more visible starting from the date+time of the event

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#181]
Typically a match is removed when the date + time of the match is before the current date + time. We should remove matches from the agenda the day after the date of the match (same for all events)

**Comment by matt-aubert** [comment]
@eric-taix : a quick question : 

When do you remove the possibility to edit a past game ? when the score was integrated into the global table or after a certain date and time ?

**Comment by eric-taix** [comment]
When the score has been entered and validated. Note : the match is removed from "Prochains événements" the day after the match but it's still visible in the agenda until validated.
