### ISSUE TITLE
Incorrect stat

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#190]
My club stat has no incomplete result in chart but I have a team with.
![Screenshot_20211216-081841.jpg](https://user-images.githubusercontent.com/3205330/146325817-8e7b8323-0719-4859-8874-ac7be3b2675b.jpg)

![Screenshot_20211216-081819.jpg](https://user-images.githubusercontent.com/3205330/146325839-40865b14-a41c-4cff-9e51-21804094cad4.jpg)

**Comment by eric-taix** [comment]
Thanks @Lo0ping . Can you explain me what's wrong here? I can't see the issue on your screenshots

**Comment by eric-taix** [comment]
I think I understood 😉. Your team has a "NT" result but this "NT" is not visible in your club stats?

Yes you're right, I have to add the NT bar in the graph

**Comment by eric-taix** [comment]
@Lo0ping Did you change something in the database? I have no more NT matches in your team and in your club.

**Comment by Lo0ping** [comment]
Yes, I have correcte my bug 😜
