### ISSUE TITLE
Display postponed matches

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#194]
Currently a postponed match is not more visible in the application and is not (currently) rescheduled.

The issue is that there is no way to edit the result of the match as it is not more visible in the application.

We could display it in the agenda until there's a result but it means that we will need to request all matches and not only in the future

**Comment by Lo0ping** [comment]
Normally, if postponed date is defined, you could have the good date if json response.

**Comment by eric-taix** [comment]
Ok thanks @Lo0ping , I'll have a look into the json response. If you have a postponed match in mind, can you give me its reference or either one of the team involved in this postponed match?

**Comment by Lo0ping** [comment]
Try with my team as3mt/Beach
Posponed match against Carnon Diables rouges in january

**Comment by eric-taix** [comment]
I tried to request the team' matches (i.e. `http://api.volley34.fr/v1/equipes/{{Equipe}}/matchs`) with `AS3MT2` :  
```json
{
        "MatchCode": "2022-M000098",
        "LibelleMatch": "Carnon Diables rouges reçoit as3mt/Beach",
        "CompetitionCode": "2022-C001",
        "Saison": 2022,
        "EquipeLocauxCode": "DIABLESR",
        "EquipeVisiteursCode": "AS3MT2",
        "EquipeVictorieuseCode": "",
        "EquipeArbitrageCode": "",
        "DateMatch": "2021-12-01T21:00:00",
        "GymnaseCode": "CARNON_ANQUETIL",
        "NomGymnase": "Gymnase ANQUETIL (Carnon)",
        "NomLocaux": "Carnon Diables rouges",
        "NomVisiteurs": "as3mt/Beach",
        "LibelleDetail": "",
        "EtatMatch_FDM": 0,
        "StatutMatchs": "0",
        "PenaliteLocaux": null,
        "PenaliteVisiteur": null,
        "CalendarEventID": "2022-CE00102",
        "NbRelance": 0,
        "Created": null,
        "Modified": null
    },
```

and also tried to request the match result (i.e. `http://api.volley34.fr/v1/equipes/{{Equipe}}/resultats`) : 
> Of course I was not able to find the match's result as it has been played. 

So none of them contains the postponed date or something that let me know that this match has been postponed and at which date. Did I miss something?

**Comment by Lo0ping** [comment]
OK, I will check, I thought that postponed informations were included

**Comment by Lo0ping** [comment]
Posponed informations are now included in match structure **AND** _filter=next_ option show return postponed matchs with future date

```
    {
        "MatchCode": "2022-M000098",
        "LibelleMatch": "Carnon Diables rouges reçoit as3mt/Beach",
        "CompetitionCode": "2022-C001",
        "Saison": 2022,
        "EquipeLocauxCode": "DIABLESR",
        "EquipeVisiteursCode": "AS3MT2",
        "EquipeVictorieuseCode": "",
        "EquipeArbitrageCode": "",
        "DateMatch": "2021-12-01T21:00:00",
        "GymnaseCode": "CARNON_ANQUETIL",
        "NomGymnase": "Gymnase ANQUETIL (Carnon)",
        "NomLocaux": "Carnon Diables rouges",
        "NomVisiteurs": "as3mt/Beach",
        "LibelleDetail": "",
        "EtatMatch_FDM": 0,
        "StatutMatchs": "0",
        "PenaliteLocaux": null,
        "PenaliteVisiteur": null,
        "CalendarEventID": "2022-CE00102",
        "NbRelance": 0,
        "Created": null,
        "Modified": null,
        "Report": {
            "MatchCode": "2022-M000098",
            "NumReport": 0,
            "LibelleMatch": "Carnon Diables rouges reçoit as3mt/Beach",
            "EquipeCode": "AS3MT2",
            "DateReport": "2022-01-12T21:00:00",
            "GymnaseCode": "CARNON_ANQUETIL",
            "Saison": 2022,
            "Created": null,
            "Modified": null
        }
    },
```

**Comment by Lo0ping** [comment]
2 extra field added

- DateMatchRevisee
- GymnaseCodeRevise

display informations of original match or postponed match  (if defined)

```
    {
        "MatchCode": "2022-M000098",
        "LibelleMatch": "Carnon Diables rouges reçoit as3mt/Beach",
        "CompetitionCode": "2022-C001",
        "Saison": 2022,
        "EquipeLocauxCode": "DIABLESR",
        "EquipeVisiteursCode": "AS3MT2",
        "EquipeVictorieuseCode": "",
        "EquipeArbitrageCode": "",
        "DateMatch": "2021-12-01T21:00:00",
        "GymnaseCode": "CARNON_ANQUETIL",
        "NomGymnase": "Gymnase ANQUETIL (Carnon)",
        "NomLocaux": "Carnon Diables rouges",
        "NomVisiteurs": "as3mt/Beach",
        "LibelleDetail": "",
        "EtatMatch_FDM": 0,
        "StatutMatchs": "0",
        "PenaliteLocaux": null,
        "PenaliteVisiteur": null,
        "CalendarEventID": "2022-CE00102",
        "NbRelance": 0,
        "Created": null,
        "Modified": null,
        "Report": {
            "MatchCode": "2022-M000098",
            "NumReport": 1,
            "LibelleMatch": "Carnon Diables rouges reçoit as3mt/Beach",
            "EquipeCode": "AS3MT2",
            "DateReport": "2022-01-12T21:00:00",
            "GymnaseCode": "CARNON_ANQUETIL",
            "Saison": 2022,
            "Created": null,
            "Modified": null
        },
        "DateMatchRevisee": "2022-01-12T21:00:00",
        "GymnaseCodeRevise": "CARNON_ANQUETIL"
    },
```

**Comment by eric-taix** [comment]
I saw that the match end point was broken few minutes ago and I was pretty sure that you were working on this feature 👍
You rock

**Comment by eric-taix** [comment]
Preview of screens. Note the "Report" badge in the upper right corner. Also in the detail I displayed the initial date.
Currently this page has an issue: the postponed match can have a different gymnasium. The postponed gymnasium's code is returned in the endpoint but not the postponed gymnasium code:
```json
   "Report": {
            "MatchCode": "2022-M000228",
            "NumReport": 1,
            "LibelleMatch": "Castelnau/6 reçoit VCV1",
            "EquipeCode": "VCVX1",
            "LocauxCode": null,
            "VisiteursCode": null,
            "DateReport": "2022-01-10T20:00:00",
            "GymnaseCode": "VAILHAUQUES_SALLE_POLYV",
            "NomGymnase": null,
            "Saison": 2022,
            "Commentaire": "",
            "Created": null,
            "Modified": null
        },
        "DateMatchRevisee": "2022-01-10T20:00:00",
        "GymnaseCodeRevise": "VAILHAUQUES_SALLE_POLYV"
```

Of course I can request the server to retrieve the gymnasium's name but it's not very efficient. @Lo0ping Can you return the `NomGymnase` attribut in the `Report` object and also return a `NomGymnaseRevise` field in the endpoint?

<img src="https://user-images.githubusercontent.com/712517/146919356-4fab0e58-5b73-4cb5-b312-96102415e845.png"  width="300">
<img src="https://user-images.githubusercontent.com/712517/146919367-f37be565-3a07-4dc9-a949-b08c80d42e5e.png" width="300">

**Comment by Lo0ping** [comment]
Done : 
{
        "MatchCode": "2022-M000228",
        "LibelleMatch": "Castelnau/6 reçoit VCV1",
        "CompetitionCode": "2022-C004",
        "Saison": 2022,
        "EquipeLocauxCode": "MJCCVX2",
        "EquipeVisiteursCode": "VCVX1",
        "EquipeVictorieuseCode": "",
        "EquipeArbitrageCode": "",
        "DateMatch": "2021-12-02T21:00:00",
        "GymnaseCode": "CASTELNAU",
        "NomGymnase": "Palais des Sports Jacques CHABAN DELMAS (Castelnau-le-Lez)",
        "NomLocaux": "Castelnau/6",
        "NomVisiteurs": "VCV1",
        "LibelleDetail": "",
        "EtatMatch_FDM": 0,
        "StatutMatchs": "0",
        "PenaliteLocaux": null,
        "PenaliteVisiteur": null,
        "CalendarEventID": "2022-CE00232",
        "NbRelance": 0,
        "Created": null,
        "Modified": null,
        "Division": null,
        "Poule": null,
        "Report": {
            "MatchCode": "2022-M000228",
            "NumReport": 1,
            "LibelleMatch": "Castelnau/6 reçoit VCV1",
            "EquipeCode": "VCVX1",
            "LocauxCode": "MJCCVX2",
            "VisiteursCode": "VCVX1",
            "DateReport": "2022-01-10T20:00:00",
            "GymnaseCode": "VAILHAUQUES_SALLE_POLYV",
            **"NomGymnase": "Salle Polyvalente (Vailhauquès)",**
            "Saison": 2022,
            "Commentaire": "",
            "Created": null,
            "Modified": null
        },
        "DateMatchRevisee": "2022-01-10T20:00:00",
        "GymnaseCodeRevise": "VAILHAUQUES_SALLE_POLYV",
        "**NomGymnaseRevise": "Salle Polyvalente (Vailhauquès)"**
    }

With all the nformations, you could put a red badge for team pospone request and green for opponent pospone request  ;-)

**Comment by eric-taix** [comment]
Does `EquipeCode` is the code of team which had request to postpone? What if both teams had request to postpone?

**Comment by eric-taix** [comment]
Also I don't see `NomGymnaseRevise` in the response for the request `equipes/{{Equipe}}/matchs?filter=next&value=4`

**Comment by eric-taix** [comment]
Not related to this issue but there's an error in the postponed information: the postponed match will  played at Castelnau Palais des sports

**Comment by matt-aubert** [comment]
> Not related to this issue but there's an error in the postponed information: the postponed match will be played at Castelnau Palais des sports

In the initial game as well, in fact the gymnase did not change

**Comment by Lo0ping** [comment]
> Does `EquipeCode` is the code of team which had request to postpone? What if both teams had request to postpone?

Yes

**Comment by Lo0ping** [comment]
... And there is no difference between 2 Teams request and no team request information because both will be forfait if the match is not played
