### ISSUE TITLE
Postpone a match

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#195]
Let the user the ability to postpone a match. For now the postpone will be sent by email with the same text.

**Comment by matt-aubert** [comment]
**2 remarks :** 

**1st :** 
A field with the "postponed date" should be available.
Otherwise, if it is foreseen to be written in "Commentaires" (it should at least be suggested then)

**2nd :** 
When you cancel the email sending, you get the "email envoyé, merci" message anyways

**Comment by eric-taix** [comment]
For the 1st comment: you're right, It be just mimic volley 34. But I can add some optional fields to set the postponed date and gymnasium?

For the 2th comment: Unfortunately even if the email is cancelled, discarded,... Gmail (and other mail client) returns ok. Only iOS mail client seems to return an appropriated code result. So what message is the best? Do you think that we must change this message to "xxxxx" ( to be defined)

**Comment by matt-aubert** [comment]
> For the 1st point: you're right, It just mimic volley 34. But I can add some optional fields to set the postponed date and gymnasium?
**Yes, good call regarding the gymnasium.
For the date if not to time consuming a typical "calendar" field. Preventing typing mistakes.**

> For the 2nd point: Unfortunately even if the email is cancelled, discarded,... Gmail (and other mail client) returns ok. Only iOS mail client seems to return an appropriated code result. So what message is the best? Do you think that we must change this message to "xxxxx" ( to be defined)
**:/ too bad ... unfortunately, if we can't be sure the email is really sent, we can't be sure to display the correct message ... I would leave it this way (as most of the time the email will be send)
Could be good to CC the sender, to confirm the email was indeed sent.**

**Comment by Lo0ping** [comment]
You can use the endpoint /v1/report/post to postpone a match.

**Comment by matt-aubert** [comment]
> You can use the endpoint /v1/report/post to postpone a match.

You mean, it does not necessarily have to be through email ?

**Comment by matt-aubert** [comment]
For v1 the postponement will be send by email. So far, it is not possible to identify the sender as a legitimate sender, and a second validation by the opposite team will also be required before making the change in the agenda. (they need to be agreed on the date)
Otherwise anyone will be able to postpone any game from any team.

**Comment by matt-aubert** [comment]
> For the 1st point: you're right, It just mimic volley 34. But I can add some optional fields to set the postponed date and gymnasium?
> 

@eric-taix : I don't see a "date" and "gymnasium" fields in this feature. Did you decide not to do it ? or is it going to be in a next release ?

**Comment by eric-taix** [comment]
These fields do not exist in Volley34 that's why I decided to not add them for this release. Does it make sense?

**Comment by matt-aubert** [comment]
> These fields do not exist in Volley34 that's why I decided to not add them for this release. Does it make sense?

ok, it was to avoid date typing mistakes from the users (and make it more friendly)
But let's push that to v2 then
