### ISSUE TITLE
Current location is not displayed

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#201]
In maps, the current location of the user is not displayed

**Comment by matt-aubert** [comment]
Still not displayed for me : Android
When I push the "target" icon, it centers the screen where I am, but no dot to indicate my position (Gymnasium screen)

**Comment by matt-aubert** [comment]
well .... now it is ... I will move it to "review in progress" and check deeper why

**Comment by eric-taix** [comment]
Did the application asked you if you agree to share your position when the application is running? This is a security requirement and your position can't be displayed until you allow it. BTW to test, you can change these security option in Applications -> Volley34 -> Authorization

I've just changed my authorization to "Always ask" and the first time the gymnasium map is displayed, when I click to "My position" button, Android asked me if I agree to share my position but the marker is not displayed. If I go away and come back to this screen then my position is displayed.

**Comment by matt-aubert** [comment]
> Did the application asked you if you agree to share your position when the application is running? This is a security requirement and your position can't be displayed until you allow it. BTW to test, you can change these security option in Applications -> Volley34 -> Authorization
> 
> I've just changed my authorization to "Always ask" and the first time the gymnasium map is displayed, when I click to "My position" button, Android asked me if I agree to share my position but the marker is not displayed. If I go away and come back to this screen then my position is displayed.

yes, I agreed when it asked, but I had to move screen and come back to see it
