### ISSUE TITLE
Send Result Endpoint

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#204]
Now you are able to send result using http://api.volley34.fr/v1/resultats/sendresult
with the following structure in the body
{
 "Id": "2022-M000089",
 "LicencesLocaux": ["916182","674807", "916189", "916186", "336003", "688495" ],
 "LicencesVisiteurs": [ "661569", "917957", "661577", "862930" ],
 "Sets": [
     { "Id": 1, "Locaux": 23, "Visiteur": 25 },
     { "Id": 2, "Locaux": 25, "Visiteur": 20 },
     { "Id": 3, "Locaux": 25, "Visiteur": 23 },
     { "Id": 4, "Locaux": 25, "Visiteur": 20 },
     { "Id": 5, "Locaux": null, "Visiteur": null }
 ],
 "IsUnfinished": false,
 "Comments": "",
 "SignLocaux": "",
 "SignVisiteurs": ""
}

- id => MatchCode
- LicencesLocaux =>  locals attendees licence number list
- LicencesVisiteurs=> visitors attendees licence number
- Sets => Match result
- IsUnfinished => For unfinished Game
- Comments => Comments area (if needed)
- SignLocaux & SignVisiteurs => Not implemented Yet

**IMPORTANT** : It's a POST method that need an x-api-key in the header (as any other POST method)

**I think that, when this method will be fully implemented (including signing with PIN Code), paper match sheet would be unnecessary for teams that use the app**

**Comment by eric-taix** [comment]
That's a very good news to see that you've started to implement this feature (Christmas before Christmas) and also a very good news for trees 😉 thanks you very much

This feature will be develop in the V2. In the meantime, I'll create a discussion in GitHub where I'll explain what I have in mind but we could also organize a meeting (physical or virtual).

Thanks again 👍👍👍

**Comment by matt-aubert** [comment]
very good news ! thanks @Lo0ping 
I move it to v2 milestone

**Comment by clapoujade** [comment]
Keep in mind that the 1.0.69.169 build does not give  access the score board for the matchs when the date is over. 
For instance, the match Gigean M2 vs AVGM1, that was played friday december 17, is no more visible, nor in the agenda tab (normal), neither in the results tab. On december 19, user cannot enter the score anymore

**Comment by eric-taix** [comment]
> This is something we already discuss outside of github, but I do not see any opened issue related to this (perhaps I missed it, but anyway I put it as a reminder:

Please could you create a new issue?

**Comment by eric-taix** [comment]
Also is there any mandatory field in the post? What if `licences` are not filled? Do you reject the request?
Can you also give the HTTP codes you can return?

**Comment by Lo0ping** [comment]
>1- Could I send the the photo of the match's sheet in this endpoint and how? Any base64 or multipart/form-data?

L'envoie des feuilles de match n'est actuelleement pas mise en place mais sera surement en base64

>2- How could I "play" and test this endpoint without disturbing the current championship?

Je vais mettre en place une version de test de l'API

**Comment by Lo0ping** [comment]
> Also is there any mandatory fields in this post endpoint? What if licences are not filled? Do you reject the request?

pas de champs obligatoires actuellement

> Can you also give me the HTTP codes you can return?

200 + ResultRequestResponse Object
404
500

**Comment by Lo0ping** [comment]
voila a quoi pourrais ressembler ton body
{
"Id": "2022-M000089",
"LicencesLocaux": ["916182","674807", "916189", "916186", "336003", "688495" ],
"LicencesVisiteurs": [ "661569", "917957", "661577", "862930" ],
"Sets": [
{ "Id": 1, "Locaux": 23, "Visiteur": 25 },
{ "Id": 2, "Locaux": 25, "Visiteur": 20 },
{ "Id": 3, "Locaux": 25, "Visiteur": 23 },
{ "Id": 4, "Locaux": 25, "Visiteur": 20 }
],
"IsUnfinished": false,
"Comments": "",
"SignLocaux": "",
"SignVisiteurs": "",
SenderName="Laurent",
SenderTeam="as3mt/Beach",
SenderMail="lau...@a...t.fr",
MatchSheetFileName = "MonFichier.ext"
MatchSheetFileBase64 =  "....."
}

**_et la Response 200 sera du style_** 
{
"MatchCode": "2022-M000089",
"LibelleMatch": "Locaux reçoit Visiteurs",
"Status" : "OK_LOCALS_WIN",
"Commentaire" : " bla bla ..."
}

**_Valeurs possibles de Status_**
- OK
- OK_WIN_LOCALS
- OK_WIN_VISITORS
- KO
- KO_INVALID_SET_NUM
- KO_INVALID_SCORE

si Status = KO... alors Commentaire aura l'explication du KO et le résultat le sera pas enregistré

**Comment by Lo0ping** [comment]
> 2- How could I "play" and test this endpoint without disturbing the current championship?

apitest.volley34.fr

cette version est connectée à une base de test dont j'ai remonté un backup de prod

**Comment by eric-taix** [comment]
Je vais m'y attaquer mais des questions : 
- est ce que l'URL de l'API de test t'envoie un mail ? 
- Dans ce cas pour ne pas perturber les vrais résultats, est ce que je rajoute un commentaire "test post API" ou un truc du genre ?
- Du fait des modifications en base (divisions, etc) est ce tu dois reprendre un autre backup afin que je puisse tester l'API de test ?

**Comment by Lo0ping** [comment]
```
est ce que l'URL de l'API de test t'envoie un mail ?
```
Oui
```
Dans ce cas pour ne pas perturber les vrais résultats, est ce que je rajoute un commentaire "test post API" ou un truc du genre ?
```
Le titre du Mail contient déjà "DEBUG MODE" mais ajout "TEST_POST_API" ton commentaire comme ça si je me trouve, je te mets en copie
```
Du fait des modifications en base (divisions, etc) est ce tu dois reprendre un autre backup afin que je puisse tester l'API de test ?
```
c'est à dire ?

**Comment by eric-taix** [comment]
Alors:

J'ai bien une `403` quand je ne mets pas le login et le token dans le header 👍 
Par contre quand j'envoie le `POST` sur `http://apitest.volley34.fr/v1/resultats/sendresult` => 
> {
    "Message": "The requested resource does not support http method 'POST'."
}

Du coup cette API + method est bien déployée sur l'api de test ?

**Comment by Lo0ping** [comment]
Salut,
Oui, elle est bien déployée.
Essayes plutôt :
`http://apitest.volley34.fr/v1/resultats/post`
Et sans les infos de header, tu dois obtenir une erreur 403 avec le message `invalid API key`

**Comment by Lo0ping** [comment]
Salut, 
comme tu as du recevoir un mail, je t'envois ci dessous la structure JSON qui m'a permis de le faire 
j'ai noté 2 differences avec la tienne
- ID au lieu de MatchCode
- Comments au lieu de Comment

```
{
    "MatchCode": "2022-M000090",
    "LicencesLocaux": [],
    "LicencesVisiteurs": [],
    "Sets": [
        {
            "Id": 1,
            "Locaux": 23,
            "Visiteur": 25
        },
        {
            "Id": 2,
            "Locaux": 18,
            "Visiteur": 25
        },
        {
            "Id": 3,
            "Locaux": 18,
            "Visiteur": 25
        },
        {
            "Id": 4,
            "Locaux": null,
            "Visiteur": null
        },
        {
            "Id": 5,
            "Locaux": null,
            "Visiteur": null
        }
    ],
    "IsUnfinished": false,
     "Comment": "TEST_POST_API: API test pour Eric ;-)",
     "SignLocaux": "",
     "SignVisiteurs": "",
    "SenderName":"Laurent",
    "SenderMail":"Laurent@as3mt.fr",
    "SenderTeam":"as3mt/Beach",
    "MatchSheetFileName": null,
    "MatchSheetFileBase64": null
}
```

**Comment by Lo0ping** [comment]
et voici la réponse qui accompagnera le code 200 

{
    "CodeMatch": "2022-M000090",
    "LibelleMatch": "AVGM 1 reçoit as3mt/Beach",
    "Commentaire": "AVGM 1 perd contre as3mt/Beach\n0-3\n23-25, 18-25, 18-25 (59-75)",
    "Status": "OK_WIN_VISITORS"
}

**Comment by eric-taix** [comment]
👍  Ok ca à l'air de marcher. Désolé je risque de "t'inonder" de mail pour tester les différents cas de figure....

**Comment by eric-taix** [comment]
L'API marche bien mais j'ai cependant un soucis quand j'essaie d'envoyer une image => `Error HTTP 500`
Ce problème fait que je ne peux mettre à disposition pour les testeurs car pas de feuille de match possible...

PS: Et après il ne reste plus que l'utilisation de l'API de report. Mais je n'arrive plus à retrouver le ticket où tu m'as donné les infos de l'API de report (à moins que j'ai rêvé)

Les données envoyées sont les suivantes
```
{
  "MatchCode": "2022-M000271", 
  "LicencesLocaux": [], 
  "LicencesVisiteurs": [], 
  "Sets": [
    {"Id": 1, "Locaux": 25, "Visiteur": 0}, 
    {"Id": 2, "Locaux": 25, "Visiteur": 0}, 
    {"Id": 3, "Locaux": 25, "Visiteur": 0}, 
    {"Id": 4, "Locaux": null, "Visiteur": null}, 
    {"Id": 5, "Locaux": null, "Visiteur": null}
  ], 
  "IsUnfinished": false, 
  "Comment": "TEST_POST_API:" , 
  "SignLocaux": "", 
  "SignVisiteurs": "", 
  "SenderName": "qqq", 
  "SenderTeam": "VLCA/A l'arrache", 
  "SenderMail": "eric.taix@gmail.com", 
  "MatchSheetFileName": "image_picker7353601173885219906.jpg", 
  "MatchSheetFileBase64": "iVBORw0KGgoAAAANSUhE... and more"
}
``` 

L'image est la suivante:
![1642120593949](https://user-images.githubusercontent.com/712517/152902065-a217759e-69d4-4da9-a82e-5065c93426bb.jpg)

L'image en base64 se trouve ici => https://gist.githubusercontent.com/eric-taix/fb661fffa611ecdd4b3067f8e47b6c2e/raw/3bdacc00de86bf97800639d72d8b05f858b89008/image.base64

Celle-ci est bien encodée en base64 (vérification possible ici => https://codebeautify.org/base64-to-image-converter)

**Comment by Lo0ping** [comment]
ça devrait être mieux maintenant
