### ISSUE TITLE
The visitor's name is not centered in match's card

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#205]
The host's name seems to be centered (to be verified) but not the visitor's name.

**Comment by eric-taix** [comment]
Ok both were not centered when the line overflowed

**Comment by matt-aubert** [comment]
The problem seems to remain : 

![names-centered](https://user-images.githubusercontent.com/95641846/148233273-f77cb541-b0e1-4a6a-b8db-adabacc14ca4.jpg)

**Comment by eric-taix** [comment]
Yes this is not exactly centered, probably due to the arrow to the right. But this issue was more about left align for the visitor's name. Here I think you can live with this "not exactly centered" no?

**Comment by matt-aubert** [comment]
> Yes this is not exactly centered, probably due to the arrow to the right. But this issue was more about left align for the visitor's name. Here I think you can live with this "not exactly centered" no?

I can live with water and a knife ;)
I'm just here to filter potential issues you did not see
