### ISSUE TITLE
Postpone Endpoint

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#206]
Hi, 
new endpoint for posponed match :

- http://api.volley34.fr/v1/reports : Get all posponed matchs informations for the current season 
- http://api.volley34.fr/v1/reports/match/{match} : Get posponed informations for the match
- http://api.volley34.fr/v1/reports/equipe/{equipe} : Get all posponed matchs informations for a team and the current season 
- http://api.volley34.fr/v1/reports/post : submit a posponed match (see body exemple below)
` {
        "MatchCode": "2022-M000107",
        "EquipeCode": "AS3MT2",
        "DateReport": "2022-01-04T19:45:00",
        "GymnaseCode": "MTP_RAMEL",
        "Commentaire" :"Test",
        "SenderName"  :"Laurent S",
        "SenderTeam" : "as3mt/Beach",
        "SenderMail":"lsangalli@as3mt.fr"
    }`

**Comment by eric-taix** [comment]
Move to release v2 as the most important information is the new end point to postpone a match.

**Comment by Lo0ping** [comment]
To Implement front-side

**Comment by eric-taix** [comment]
@Lo0ping 
Pour le report d'un match les champs suivants sont-ils obligatoires (car pour l'instant je ne les saisie pas) ?
- `DateReport`
- `GymnasiumCode`

Et concernant l'attribut `EquipeCode`, si c'est les 2 équipes qui demandent le report, je mets `""` (chaine vide), `null` ou `all` ou `both` ou autre chose ?

**Comment by Lo0ping** [comment]
```
DateReport
GymnasiumCode
```
ne sont effectivement pas obligatoires

la notion des 2 équipes qui demandent le report n'existent plus. qu'elle se mettent d'accord sur le report, c'est une chose.
mais il y a toujours une équipe qui contacte l'autre pour l'envisager ...

**Comment by Lo0ping** [comment]
je viens de deployer et tester
je report est bien saisi mais pas de commentaire (champs oublié ?) et pas de mail (ça s'est très étrange)

**Comment by Lo0ping** [comment]
appel de l'api avec 
```
{
    "MatchCode": "2022-M000482",
    "EquipeCode": "AVGM1",
    "DateReport": null,
    "GymnaseCode": "MTP_RAMEL",
    "Commentaire": "Test",
    "SenderName": "Laurent S",
    "SenderTeam": "as3mt/Beach",
    "SenderMail": "lsangalli@as3mt.fr"
}
```
mail reçu 

![image](https://user-images.githubusercontent.com/3205330/153048714-e111417f-2cf6-4367-9c9a-fa2cd5d17716.png)
