### ISSUE TITLE
Score board edit box accept wrong values

### ISSUE THREAD

**Issue by clapoujade** [eric-taix/volley34-mobile#207]
It is possible to enter invalid scores (i.e. '1.4', or '-2').
Is it possible to prevent wrong values, instead of checking them on score submition?

**Comment by eric-taix** [comment]
👍 I forgot to check negative numbers. Yes I think it is possible. 

And for your information, the fields are validated on the fly and not when the score is submitted: there is a red border when a field is invalid, this border can change as soon as you enter a character.

**Comment by Lo0ping** [comment]
Is it normal that I don't see this feature ?

**Comment by matt-aubert** [comment]
> Is it normal that I don't see this feature ?

@Lo0ping : see #147, so far you can only see it when you enter a game from the agenda of **your Dashboard**.
Circular menu bottom right.

**Comment by eric-taix** [comment]
He should be able to enter the score from anywhere in the application no matter where he comes from no? The issue you mentioned @matt-aubert is just to download the official score sheet except if I missed something

**Comment by eric-taix** [comment]
![Screenshot_20211221-110914.jpg](https://user-images.githubusercontent.com/712517/146911964-92e1017c-73dd-4313-b16b-ba3de00823d2.jpg)

**Comment by matt-aubert** [comment]
> He should be able to enter the score from anywhere in the application no matter where he comes from no? The issue you mentioned @matt-aubert is just to download the official score sheet except if I missed something

Yes you're right sorry, I mixed up with the "download sheet" option.

The pencil icon is accessible from any "game" even if this is not your own team

**Comment by clapoujade** [comment]
Other kind of wrong values:
![Uploading IMG_20211222_133856.jpg…]()

**Comment by matt-aubert** [comment]
@clapoujade : it seems there is something wrong with your post (can't see your image)

**Comment by clapoujade** [comment]
> @clapoujade : it seems there is something wrong with your post (can't see your image)

Yes indeed: to sum up, it is possible to enter a match
with 4-0 and a set score with 52-3. Does the validation on submition prevent such erroneous fields values ?

**Comment by clapoujade** [comment]
As a reminder : A screen shot of a score mail (After score submition) showing several errors that went through score board validation
![IMG_20211223_141216](https://user-images.githubusercontent.com/95589274/147245835-ba1c0f5f-2554-40b8-b34e-f1559d11d318.jpg)

**Comment by eric-taix** [comment]
No currently the validation won't prevent such errors (52-3 & 4-0): it's the responsibility of the submitter to check. 
I just added (In the next version) negative input prevention and also not more than 2 digits.

Why?: there are many other rules that can be checked, and I don't want to waste my time with these rules for now 😜

**Comment by eric-taix** [comment]
But I will check if I can add some checks 😉

**Comment by Lo0ping** [comment]
> As a reminder : A screen shot of a score mail (After score submition) showing several errors that went through score board validation
> ![IMG_20211223_141216](https://user-images.githubusercontent.com/95589274/147245835-ba1c0f5f-2554-40b8-b34e-f1559d11d318.jpg)
> 

Actually, there is no space around - and no space before , in score detail.

And for information, all the time you spend here has already used to implément post api... That also validate result, send mail,... 😉

**Comment by matt-aubert** [comment]
note : 
- Prevent negative numbers
- prevent 3 digits numbers

**Comment by eric-taix** [comment]
This has been fixed in version 1.1.0

**Comment by matt-aubert** [comment]
> This has been fixed in version 1.1.0

yes I know ... I'm just commenting what was the final fix for this issue. As sometimes, reading the thread makes it difficult to know what to test in the end

So if I add a "note" and the status is "review approved" it means that this is "closed" from my side

**Comment by eric-taix** [comment]
Sorry didn't see the status :-( , I 've just answered to the Github email
