### ISSUE TITLE
Display competitions results

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#208]
The competition page should display a page with as many tabs as there are different competitions.
At least the UI should be the same as the ranking table, but it could really cool to find a way to display almost all values displayed on the web site.

Some extra features:
- It should be awesome to be able to filter the division, the gender (M-M, M-F or F-F), the number of players (4x4 or 6x6), ...
- It should also be awesome to be able to search for a team's name

**Comment by matt-aubert** [comment]
Just to provide some visual and first inputs : 

- As the original table contains multiples columns, I was thinking of forcing the display in "landscape" when selecting the "compétitions" button.

- Below a "draft" (don't focus on design, I agree this does not look nice)

![image](https://user-images.githubusercontent.com/95641846/146967703-93dd4c60-9963-4532-bedb-8e210cc194fb.png)

Rechercher : allows the user to look for teams
Filtrer : allows the user to filter on : 
       - Category (excellence, promotion etc.)
       - Type of play (4x4 mix, men, women, 6x6 mix, men, women)

Now that I have built the draft, I can easily modify the visual.

**Comment by Lo0ping** [comment]
If you fix column, you can have a portrait view withou D. Sets and D. Pts, and full ranking on landscape view.
That I made in my (RIP) version of volley 34 for Windows phones

**Comment by eric-taix** [comment]
Thanks for this draft.

The main issue with mobile is the width, look at the ranking table in the teams details : we are only able to display teams name and 2 columns. This let me think that, as  @Lo0ping said, we probably have to have 2 layouts according to the mobile orientation: simple and added advanced. 

For the filter, I was thinking about something like Google maps (see the screenshot)![Screenshot_20211221-184243_Maps.jpg](https://user-images.githubusercontent.com/712517/146974874-5a444080-a643-452b-9f6e-5eedb67748b8.jpg)

Also I think the user should be able to search for a team.

**Comment by matt-aubert** [comment]
I agree for the 2 layouts : 
- simple view in portrait (without D.Sets & Pts)
- advanced view in landscape (all columns)

Yes the user should be able to search for a team.

It seems there are 2 types of filter mentioned here : 

**1. Predefined filters, that can include :** 
     - categories (excellence, promotion etc.)
     - type of play (4x4 mix, 6x6 etc.)

Filter icon is always visible.
You can filter without typing in the search field and display only what you're looking for.

**2. Filters based on results : (the google maps example)**

Filter icon is only visible after a search.
You can filter on the results of your search.

ie : if you search for VCV, you won't be able to filter on "type of play" since there are only 4x4 mix teams in this club
But you will be able to filter on categories ( excellence, etc.)

my opinion : 
The type 2 seems more efficient to find exactly what you search.
Type 1 allows you to display all tables for a given filter (category, type of play ... )

**Comment by clapoujade** [comment]
Filtering and search are advanced features to my mind (many controls are required)
Unless you already started this dev, would it be preferable to have collection of favorites + the toggle 'show all'/'show only favorites'

**Comment by eric-taix** [comment]
I've started to implement this feature (almost finished).

Finally I've implemented the first option as the second one requires much more work! I also think that filters should be independent of the search option. I'd also display filtering options in a bottom sheet, which is by the way, how filters are displayed.

Screenshots:
![Screenshot_1640692066](https://user-images.githubusercontent.com/712517/147570613-7f883c9d-823e-4756-ac0b-9946567801d4.png)
![Screenshot_1640692058](https://user-images.githubusercontent.com/712517/147570624-a38b439b-fda6-4799-b95d-3bbbd7829a9f.png)

**Comment by Lo0ping** [comment]
Some rankings are wrong...
![Screenshot_20211229-025940.jpg](https://user-images.githubusercontent.com/3205330/147620338-315d9a60-e1a0-42ca-ac4d-3791e62d224c.jpg)

I let you find why 😉...

**Comment by eric-taix** [comment]
Was it a joke regarding your personal ranking ? I'm not able to find the wrong rankings and it seems to be the same values as Volley34.

**Comment by clapoujade** [comment]
Not a joke, Line 4 and 5 are inverted if we compare with volley34

**Comment by eric-taix** [comment]
Good catch 👍 I know why, will fix it!

**Comment by Lo0ping** [comment]
Ha.. Ha... Not a joke at all... 

Ranking must be sorted by total desc, diffset desc and diffpoint desc.

I have seen an other similar issues with on team of Clapiers (4x4 mixte-honneur poule 2)

**Comment by Lo0ping** [comment]
Other details, all rankings are displayed at the same time and the same,here championnat and challenge.
Could you use separate tabs, for example.
You could display by default the current tabs using competitions dates?

**Comment by eric-taix** [comment]
> Ha.. Ha... Not a joke at all...
> 
> Ranking must be sorted by total desc, diffset desc and diffpoint desc.
> 
> I have seen an other similar issues with on team of Clapiers (4x4 mixte-honneur poule 2)
> 
> But I don't understand why that happened, I give you rank position in the API.

Yes I made a mistake, I've sorted by `TotalPoints` instead of sorting by `Rank`. I've fixed this issue

**Comment by eric-taix** [comment]
> Other details, all rankings are displayed at the same time and the same,here championnat and challenge. Could you use separate tabs, for example. You could display by default the current tabs using competitions dates?

It was my initial implementation, but I've encountered an issue using tabs in main pages! So I've implemented a filter which opens in the bottom sheet which was more easy for me. By default I display all competitions as Volley does, but the user can tap on the filter button (top right corner) to filter competition(s) and division.

**Comment by eric-taix** [comment]
Also note I was not far from being able to filter `Division` , `Group` , ... only with the search field.

Example: If looking for the excellence 4x4 male, then the user should only fill the search bar with `Excellence 4x4 Masculin` or `Excellence Masculin 4x4` or .... 
But I gave up because of not enough time. I think it can be a good user experience but we can postpone this feature to a future release.
