### ISSUE TITLE
Team screen - indicators reorganization

### ISSUE THREAD

**Issue by matt-aubert** [eric-taix/volley34-mobile#209]
**Stats globales :** 

- Classement
- tableau classement
- force

**Stats détaillées :**

- victoires
- Scores
- Diff de sets
- set pris
- diff de points

@eric-taix : not quite sure this is precisely what we discussed ...

**Comment by eric-taix** [comment]
No 😂 I think it was

Classements
- ranking
- ranking table

Statistiques générales
- Victoires
- Scores
- Forces

Statistiques détaillées
- Diff. Sets
- Sets pris
- Points pris

**Comment by eric-taix** [comment]
But I like "Stats globales" instead of "Stats générales"

**Comment by matt-aubert** [comment]
ok 😄 looks better like this
