### ISSUE TITLE
For a given match, user cannot access to the score board 2 days after the scheduled date

### ISSUE THREAD

**Issue by clapoujade** [eric-taix/volley34-mobile#210]
The 1.0.69.169 build does not give access the score board for the matchs when the date is over.
For instance, as the match Gigean M2 vs AVGM1, that was played friday december 17 is no more visible on december 19 ( agenda tab & results tab), user cannot enter the score anymore

**Comment by matt-aubert** [comment]
@eric-taix : it can match one of our discussions on that topic : 

Keeping all games in the agenda, but with a rule that displays first the next game/event from the current date
Access to the former games is made by scrolling

**Comment by eric-taix** [comment]
Yes it can. The only issue I can see is that for now to retrieve postponed matches I need to use the `next` filter in the end point (which does not return the past matches). @Lo0ping do you think you can return postponed matches but without the `next` filter?

I can also use 2 endpoints but it won't be very efficient for the server.

Also we have to think if we want to display all matches in the past, only matches in the past which do not have a result. And also if the UI is the same for past matches.

**Comment by eric-taix** [comment]
I've just thought that we can also add a switch "Afficher tous les matchs" which will request the server for past matches only when it's on.

**Comment by clapoujade** [comment]
@eric-taix this was my expectation in the results tab.
This would means that the past matches would have a different look and feel showing that the relative score could be entered from them

**Comment by Lo0ping** [comment]
@eric-taix , Look at the new  endpoint ;-)

**Comment by matt-aubert** [comment]
> @eric-taix my initial expectation was the results tab. Past matches without score would have a different look and feel (the clickable pencil icon for instance) showing that the relative score can be entered from there

Perhaps it is not relevant to display a game without result yet in the "result" tab, or is it ?

To be discussed ...

**Comment by matt-aubert** [comment]
> Yes it can. The only issue I can see is that for now to retrieve postponed matches I need to use the `next` filter in the end point (which does not return the past matches). @Lo0ping do you think you can return postponed matches but without the `next` filter?
> 
> I can also use 2 endpoints but it won't be very efficient for the server.
> 
> Also we have to think if we want to display all matches in the past, only matches in the past which do not have a result. And also if the UI is the same for past matches.

To me : Display all games with different UI when past
Perhaps adding a "pencil" icon on the tile if it is a past game that requires result

**Comment by Lo0ping** [comment]
@matt-aubert, in main page, what is the goal to show all matchs ? none for me.
but in the Team page, of course yes 👍 

@eric-taix, normally next filter show matchs (posponed or not) with a future date (it use DateMatchRevisee)

**Comment by matt-aubert** [comment]
> @matt-aubert, in main page, what is the goal to show all matchs ? none for me. but in the Team page, of course yes 👍
@Lo0ping : I agree, maybe renaming the section on the Dashboard : "Agenda" by "Next event" (since no past event visible)
And leave to "Agenda" in the team's screen
@eric-taix : wdyt ?

**Comment by eric-taix** [comment]
Just your information the next events section in the dashboard only shows events for the next 4 weeks.
If the user want to see more events in the future he had to open the team's agenda. The 4 weeks is what is implemented today and we can change this value if you think it's better. I used it because I think that using a lower value won't give the user enough vision of the future and a higher value will be perhaps too much for this screen. WDYT ?

**Comment by eric-taix** [comment]
> @eric-taix, normally next filter show matchs (posponed or not) with a future date (it use DateMatchRevisee)

Yes I know for the `next` filter and it works fine. But to reduce the amount of data in the dashboard I'm using the following request `equipes/{{Equipe}}/matchs?filter=weeks&value=4` and this request does not return postponed matches.

**Comment by matt-aubert** [comment]
> Just your information the next events section in the dashboard only shows events for the next 4 weeks. If the user want to see more events in the future he had to open the team's agenda. The 4 weeks is what is implemented today and we can change this value if you think it's better. I used it because I think that using a lower value won't give the user enough vision of the future and a higher value will be perhaps too much for this screen. WDYT ?

Fine to me. Please note that what you call "next event section" is currently named "Agenda", so that would make sense to modify that title. Then, the user won't expect the possibility to scroll in the past

**Comment by Lo0ping** [comment]
> > @eric-taix, normally next filter show matchs (posponed or not) with a future date (it use DateMatchRevisee)
> 
> Yes I know for the `next` filter and it works fine. But to reduce the amount of data in the dashboard I'm using the following request `equipes/{{Equipe}}/matchs?filter=weeks&value=4` and this request does not return postponed matches.
> 

Not yet 😉

**Comment by Lo0ping** [comment]
> > @eric-taix, normally next filter show matchs (posponed or not) with a future date (it use DateMatchRevisee)
> 
> Yes I know for the `next` filter and it works fine. But to reduce the amount of data in the dashboard I'm using the following request `equipes/{{Equipe}}/matchs?filter=weeks&value=4` and this request does not return postponed matches.

Done

**Comment by eric-taix** [comment]
@Lo0ping Don't know if it's related but `http://api.volley34.fr/v1/equipes/{{Equipe}}/resultats`is down (Error 500)

**Comment by Lo0ping** [comment]
> @Lo0ping Don't know if it's related but `http://api.volley34.fr/v1/equipes/{{Equipe}}/resultats`�is down (Error 500)

No it wasn't ... It's done

**Comment by eric-taix** [comment]
My ideas about implementing the agenda tab with past events :

- as mentioned by @matt-aubert, display the first event in the future. If the user wants to see past events then he will have to scroll up.
- instead of using a pencil icon (or anything else) to indicate that a (not postponed) past match has no result, keep the current design (a clickable card)
- for past matches with a result, use a different design : no card, perhaps with a small border / dashed border / ... (to be defined). This card won't be clickable. Teams forces won't be displayed and the label between teams will be "a reçu" instead of "reçoit" 
- postponed matches are displayed as normal matches (within a card) with a postponed badge at the upper right corner

**Comment by clapoujade** [comment]
@eric-taix looks good to me 😉

**Comment by eric-taix** [comment]
Something like that (missing teams force in future matches in this screenshot) :
![Screenshot_1640251524](https://user-images.githubusercontent.com/712517/147219146-3b8cff85-e5f8-4d4d-9823-bb20c23e857a.png)

**Comment by eric-taix** [comment]
I'm just wondering if we need to indicate to the user that he can scroll up and how we can indicate it? Because it's not obvious to know that there can be events above.
Any ideas are welcome!

**Comment by matt-aubert** [comment]
> I'm just wondering if we need to indicate to the user that he can scroll up and how we can indicate it? Because it's not obvious to know that there can be events above. Any ideas are welcome!

To me, that is not really necessary, people are born-scrollers nowadays 😄

However, a "dissolve" effect could do the trick ? it shows that "there is more" but scroll to see.

**Comment by clapoujade** [comment]
> > I'm just wondering if we need to indicate to the user that he can scroll up and how we can indicate it? Because it's not obvious to know that there can be events above. Any ideas are welcome!
> 
> To me, that is not really necessary, people are born-scrollers nowadays 😄
> 
> However, a "dissolve" effect could do the trick ? it shows that "there is more" but scroll to see.

Or just display the very bottom of the previous in the match collection, so the user will understand that there is something to reveal if he scrolls up

**Comment by clapoujade** [comment]
> Something like that (missing teams force in future matches in this screenshot) Note: I tried without a border, but it feels like there's missing something
> 
> ![Screenshot_1640251524](https://user-images.githubusercontent.com/712517/147219146-3b8cff85-e5f8-4d4d-9823-bb20c23e857a.png)

proposal for postponned icon: a small arrow above or below the R could make the icon a bit more meaningful 
Where is displayed the New date for postponned match? Is this on the left side of the match panel? Or user must click on it to see it?

**Comment by eric-taix** [comment]
Arrow won't be meaningful I think, as this is a clickable card which is enough. Postponed badge is just a reminder but this is a regular match you can postpone (again) or send result.

The postponed date is displayed below the visitor's name as normal match.
