### ISSUE TITLE
Info when a new version is available

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#213]
Display a pop-up at startup when a new version is available in the store.

This is a must have feature as users can be informed and can install the latest version and don't still use an older version with less features and more bugs

**Comment by eric-taix** [comment]
Unfortunately, we won't be able to validate this issue until the second production release. The version and build number are only available when the application is released (version and build versions are not available for beta versions!)

**Comment by clapoujade** [comment]
Many app proceed to automatic upgrade? (Sometimes silent) Not possible in a v2 ?

**Comment by eric-taix** [comment]
> Soms apps proceed to automatic upgrade (Sometimes silent). Not possible in a v2 ?

An app can't upgrade itself. But the user can enable automatic update (or not) for an application in the store application which is different. There's no way, in my current knowledge, to enable an application to upgrade itself that's why to avoid too many versions installed, I have implemented this feature

**Comment by clapoujade** [comment]
Most of the game apps are doing auto upgrade at startup. But this is
probably a complex implementation: ROI is most probably too low

Le mer. 19 janv. 2022 à 15:00, Eric Taix ***@***.***> a
écrit :

**Comment by eric-taix** [comment]
Games are a bit different: the app game contains the engine but levels, sprites, perks are downloaded at startup. This is why you think that the game has been updated automatically. It's a bit like if volley 34 mobile app has been developed with WebViews (seem to be native pages but these are web pages displayed in a native page): you're are able to update the web pages without upgrading the app itself.

But this is not the case for native apps which do not use WebViews for sure.
