### ISSUE TITLE
Logo for stores

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#216]
I need the Volley34 logo as SVG to be able to scale it according to stores requirements. 
@Lo0ping Do you have the logo in SVG or at least the logo in PNG 1024x1024 ?

**Comment by Lo0ping** [comment]
Merry Christmas ! 
[Icon Volley 34.zip](https://github.com/eric-taix/volley34-mobile/files/7775651/Icon.Volley.34.zip)

**Comment by eric-taix** [comment]
Thanks, merry Christmas too

**Comment by eric-taix** [comment]
Unfortunately, when i'm opening the SGV file with Inkscape, it does not open very well. Can you export me this file with a definition of 1024x1024 please (PNG format)? Thanks

**Comment by Lo0ping** [comment]
Strange !!!
![icon-Volley34](https://user-images.githubusercontent.com/3205330/147404773-b4ce28e3-bb10-4f0b-b023-abe4de32be96.png)
