### ISSUE TITLE
Items too large

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#217]
In the dashboard, with force icons, calendar items are too large for me 
![Screenshot_20211225-092943.jpg](https://user-images.githubusercontent.com/3205330/147381074-5ab0180f-18be-461f-9648-43b14e1c7527.jpg)

Here I Just see to events on a xide screen.
Could you consider to rollback to simplest items for the dashboard ?

**Comment by eric-taix** [comment]
I was considering that too. Another consideration was that there are too many informations in this screen (dashboard) with forces displayed

**Comment by matt-aubert** [comment]
note : forces have been hidden from both agenda screens.
It is possible to display the force in the agenda through the "preferences"

**Comment by eric-taix** [comment]
> note : forces have been hidden from both agenda screens. It is possible to display the force in the agenda through the "preferences"
👍  It is a regression I've introduced. My goal was just to hide the forces in the dashboard and always keep visible the forces in the agenda. But I can also add a preference to display or not forces in teams agenda. WDTY?

**Comment by matt-aubert** [comment]
> > note : forces have been hidden from both agenda screens. It is possible to display the force in the agenda through the "preferences"
> 
> 👍 It is a regression I've introduced. My goal was just to hide the forces in the dashboard and always keep visible the forces in the agenda. But I can also add a preference to display or not forces in teams agenda. WDTY?

Ah ok ... I though it was meant to be like this. Well, I think it is fine by default.
At the origin, the forces were only going to be displayed in the "match" screen.

So fine to me like this
