### ISSUE TITLE
Discussion autour du design de l'application

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#22]
Suite à la PR #21 je pense que l'icone de l'application devrait être mis au gout du jour: l'icone est trop précise et je pense que l'on peut faire quelque chose de plus contemporain, plus simple.

Question: on est obligé de garder FSGT ? Si on met juste Volley34 (sans forcément mettre "Volley": il faut d'ailleurs éviter du texte dans les icones)

**Comment by Lo0ping** [comment]
> Question: on est obligé de garder FSGT ?
Volley 34 n'est pas FSGT donc non, aucune obligation bien au contraire, FSGT n'a pas a apparaitre

**Comment by Lo0ping** [comment]
J'aime bien l'icone moi :(

**Comment by eric-taix** [comment]
On en rediscutera ;-)

**Comment by Lo0ping** [comment]
Je te propose d'élargir la discussion au design de l'application

**Comment by eric-taix** [comment]
Yes soit on discute ici soit on se fait un call

**Comment by Lo0ping** [comment]
Je vais te présenter mon idée et on en discute

**Comment by eric-taix** [comment]
Je ferme cette issue pour faire le ménage
