### ISSUE TITLE
Field Pool is not filled for some teams

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#221]
When requesting the ranking for a team (i.e. `http://api.volley34.fr/v1/Classements/equipes/{{equipe_code}}`, the response should contain the `Division` and the `Poule`. It seems to work well for a lot of teams but for some the `Poule` field has a value of `0` which does not seem to be the right value.

Example: 
I'm requesting a team's ranking for `SGVBF`. The response is (see the `Poule` field)
```json
        "ClassementCode": "2022-C006-EX-0",
        "Libelle": "Championnat 2022 - 4x4 Féminin",
        "CompetitionCode": "2022-C006",
        "Division": "EX",
        "Poule": "0",
        "Personnalise": false,
        "Promus": 2,
        "Relegue": 2,
        "Saison": 2022,
        "Created": null,
        "Modified": null,
        // and more
```
Then when I try to retrieve all results for this division and pool with `http://api.volley34.fr/v1/resultats/2022-C006/1/0` the result is
```json
[]
```
but if I try to request the pool `1` (i.e. `http://api.volley34.fr/v1/resultats/2022-C006/1/1`) then the result contains values and some are results for the team `SGVBF`!

It seems to be related to issue #220 (may be because this competition do not have pool?) and prevent from displaying pages.

**Comment by Lo0ping** [comment]
I'll check..

Indeed, competitions with no group have `0` as `poule` number

**Comment by eric-taix** [comment]
Yes it makes sense but what I can't figure out is why when I request the pool `0` to retrieve matches results then the payload is an empty array!
