### ISSUE TITLE
Sum of NbSets_X is not equal to Joue

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#224]
I've seen strange results from the API. For the team SGVBF the request `http://api.volley34.fr/v1/Classements/equipes/SGVBF` returns:
```json
 "ClassementCode": "2022-C006-EX-0",
                "EquipeCode": "SGVBF",
                "Saison": 2022,
                "Rang": 1,
                "Nom": "SGVB/F",
                "Joue": 6,
                "Gagne": 6,
                "Perdu": 0,
                "Forfait": 0,
                "Total": 18,
                "SetP": 18,
                "SetC": 2,
                "SefDiff": 16,
                "PointsP": 470,
                "PointsC": 220,
                "PointDiff": 250,
                "Division": "EX",
                "Poule": "0",
                "Created": null,
                "Modified": null,
                "CodeCompetition": null,
                "NbSets_30": 3,
                "NbSets_31": 0,
                "NbSets_32": 1,
                "NbSets_23": 0,
                "NbSets_13": 0,
                "NbSets_03": 0,
                "NbSets_MI": 0,
                "CodeClub": null
```
If you compute the sum of `NbSets_x` (i.e. 4), this is not equal to Joue (i.e. 6). Also if you compute the number of sets won using `NbSets_x` (i.e. 3x3+3 = 12), it is not equal to `SetP` (and same if you compute the number of sets lost.
It seems there's 2 matches missing.

**Comment by Lo0ping** [comment]
NbSets_XY are wrong name. it represent nb of matchs with the result X-Y .
I'll check but I think that  forfait matchs are missing

**Comment by eric-taix** [comment]
Missing forfeit make sense because this team played against ASVBM twice and ASVBM is forfeit everytime (4 + 2 = 6).
But in the results pages, forfeits are displayed as 3-0 (25-0, 25-0, 25-0) si perhaps you can count forfeits in `Sets_30` ?

**Comment by Lo0ping** [comment]
`{
                "ClassementCode": "2022-C006-EX-0",
                "EquipeCode": "SGVBF",
                "Saison": 2022,
                "Rang": 1,
                "Nom": "SGVB/F",
                "Joue": 6,
                "Gagne": 6,
                "Perdu": 0,
                "Forfait": 0,
                "Total": 18,
                "SetP": 18,
                "SetC": 2,
                "SefDiff": 16,
                "PointsP": 470,
                "PointsC": 220,
                "PointDiff": 250,
                "Division": "EX",
                "Poule": "0",
                "Created": null,
                "Modified": null,
                "CodeCompetition": "2022-C006",
                "NbSets_30": 3,
                "NbSets_31": 0,
                "NbSets_32": 1,
                "NbSets_23": 0,
                "NbSets_13": 0,
                "NbSets_03": 0,
                "NbSets_MI": 0,
                "NbSets_3F": 2,
                "NbSets_F3": 0,
                "CodeClub": "SGVB",
                "NomCompetition": "Championnat 2022 (Brassage) - Féminin 4x4 ",
                "TypeCompetition": "CH"
            }`

You have now 2 more fields : 

- NbSets_3F : for matchs winned by forfait
- NbSets_F3 : for matchs losed by forfait or general forfait of the match for the 2 teams
