### ISSUE TITLE
404 Not found when requesting ASVBMF1's club

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#225]
When I request `ASVBMF1`'s club (i.e. http://api.volley34.fr/v1/equipes/ASVBMF1/club), the server returns a 404 Not found error.

**Comment by Lo0ping** [comment]
I have deactivated club because they are no longer playing our competitions.
I check

**Comment by Lo0ping** [comment]
It seems to work again

**Comment by eric-taix** [comment]
Yes it works 👍
