### ISSUE TITLE
Wrong match result sets

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#231]
When a match has 5 sets then the total count of sets per team is wrong : the last set with 15 points is not taken into account as a won set

**Comment by Lo0ping** [comment]
Pourquoi ne pas utiliser l'API pour vérifier la validité du résultat ?
toutes les règles sont déjà implémentée

**Comment by eric-taix** [comment]
Le but n'est pas de réécrire les règles par contre éviter à l'utilisateur de devoir envoyer son résultat pour voir si sa saisie est bonne ou pas.
