### ISSUE TITLE
Mail recipient

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#232]
Change the mail recipient for match's report and match's result to resultat@volley34.fr

**Comment by matt-aubert** [comment]
@Lo0ping : we have a game tonight, we will test the "send result" functionality : 

Will you be able to confirm and validate when received and processed ?

It's against Castelnau 6

Thanks

**Comment by Lo0ping** [comment]
Salut, (toujours en grève d'Anglais :P)
dans la mesure ou l'appli va juste ouvrir ton client mail avec un message pré-rempli, si tu passes cette étape, il n'y a pas de raison que je ne recevoir pas de mail ;) 
je vais essayer de surveiller mes mails dans la soirée ...

**Comment by matt-aubert** [comment]
> Salut, (toujours en grève d'Anglais :P) dans la mesure ou l'appli va juste ouvrir ton client mail avec un message pré-rempli, si tu passes cette étape, il n'y a pas de raison que je ne recevoir pas de mail ;) je vais essayer de surveiller mes mails dans la soirée ...

Oui, c'est juste un double check sur ce point qui est primordial à l'expérience utilisateur.
Et ca sera la première vraie interaction entre l'appli et volley34. Donc je préfère que ca soit bien validé ;)
merci
