### ISSUE TITLE
Wrong postponed gymnasium code

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#236]
I'm not sure of this issue I've already talk about but I prefer to open a specific issue.
The VCV1 and Castelnau/6 have reported a match. 

The match was planned the 02/12/2021 at Castelnau (see the first part of the response of `http://api.volley34.fr/v1/equipes/{{Equipe}}/matchs`:
```json
        "MatchCode": "2022-M000228",
        "LibelleMatch": "Castelnau/6 reçoit VCV1",
        "CompetitionCode": "2022-C004",
        "Saison": 2022,
        "EquipeLocauxCode": "MJCCVX2",
        "EquipeVisiteursCode": "VCVX1",
        "EquipeVictorieuseCode": "",
        "EquipeArbitrageCode": "",
        "DateMatch": "2021-12-02T21:00:00",
        "GymnaseCode": "CASTELNAU",
        "NomGymnase": "Palais des Sports Jacques CHABAN DELMAS (Castelnau-le-Lez)",
        "NomLocaux": "Castelnau/6",
        "NomVisiteurs": "VCV1",
        "LibelleDetail": "",
        "EtatMatch_FDM": 0,
        "StatutMatchs": "0",
        "PenaliteLocaux": null,
        "PenaliteVisiteur": null,
        "CalendarEventID": "2022-CE00232",
```

The match was postponed the 10/02/2022 (the gymnasium did not change) and I don't know who postpone the match. The postpone part of the API response is the following:
```json
         "Report": {
            "MatchCode": "2022-M000228",
            "NumReport": 1,
            "LibelleMatch": "Castelnau/6 reçoit VCV1",
            "EquipeCode": "VCVX1",
            "LocauxCode": "MJCCVX2",
            "VisiteursCode": "VCVX1",
            "DateReport": "2022-01-10T20:00:00",
            "GymnaseCode": "VAILHAUQUES_SALLE_POLYV",
            "NomGymnase": "Salle Polyvalente (Vailhauquès)",
            "Saison": 2022,
            "Commentaire": "",
            "Created": null,
            "Modified": null,
            "Status": "OK_REPORT_COMPLETE",
            "AsResult": false
        },
        "DateMatchRevisee": "2022-01-10T20:00:00",
        "GymnaseCodeRevise": "VAILHAUQUES_SALLE_POLYV",
        "NomGymnaseRevise": "Salle Polyvalente (Vailhauquès)"
```

I don't know if it's just a mistake:
  - when our team or Castelnau/6 asked to postpone the match
  - when editing the postponed informations on the server
  - or when computing the answer in the endpoint

Note: the `LocauxCode` in the `report` partis `MJCCVX2` so except if I did not understand what means "locaux" but the gymnasium's code should be `CASTELNAU`.

But the consequence is important as the application displays the wrong gymnasium. Of course this is probably a human error but I think we should be sure that this not due to a computing mistake in the endpoint

**Comment by Lo0ping** [comment]
Salut (je fais grève de l'anglais 😜)
Comme tu l'indiques, il y a peut-être eut une erreur de saisie sur le choix du gymnase.
Par contre dans l'organisation de la rencontre officielle, l'équipe locale qui gère l'organisation du match reste celle initialement prévue, quelle que soit le lieu de rencontre... Donc ici Castelnau...
Pour ma part, il n'y a pas d'erreur dans ce que tu montres.

**Comment by eric-taix** [comment]
Pas de soucis pour la grève ;-)

Du coup je ne suis pas sur de comprendre ta réponse : le gymnase de report étant Vailhauques donc j'affiche bien la salle de Vailhauques pour le match ?

Je crois que Matt a créé un ticket pour saisir une date de report et le gymnase pour la prochaine version

**Comment by Lo0ping** [comment]
`Du coup je ne suis pas sur de comprendre ta réponse : le gymnase de report étant Vailhauques donc j'affiche bien la salle de Vailhauques pour le match ?`

Si ce sont les infos du report, oui ... 
je vais corriger la salle ce soir, si le match ne se joue pas chez vous (c'est peut être moi qui ait mal saisi le report).

`Je crois que Matt a créé un ticket pour saisir une date de report et le gymnase pour la prochaine version`

J'ai vu, c'est d'ailleurs prévu dans l'API et dans le futur site web ...

**Comment by matt-aubert** [comment]
> Je crois que Matt a créé un ticket pour saisir une date de report et le gymnase pour la prochaine version
oui c'est #235 

Je viens de vérifier avec Mag et le match a toujours été prévu à Castelnau, ils ont deux créneaux Jeudi et Lundi.
C'est nous qui avons soumis le report, peut-être que la confusion vient de là.

**Comment by eric-taix** [comment]
Ok je ferme ce ticket et si on a un doute sur un autre report il sera toujours temps de le ré-ouvrir ou dans ouvrir un autre en mettant un lien sur celui-ci.
