### ISSUE TITLE
Modification format endpoint de stat des clubs

### ISSUE THREAD

**Issue by eric-taix-teads** [eric-taix/volley34-mobile#26]
Actuellement les stats d'un club sont sous le format suivant:
```json
{
  "Club": {
    ...
  },
  "Statistiques": {
    "VCV/6": {
      "Matchs": 14,
      "MatchsJoues": 12,
      "MatchsDomicile": 6,
      ...
    },
    "VCV/ Les Diablotins": {
      "Matchs": 8,
      "MatchsJoues": 9,
      "MatchsDomicile": 5,
      ...
    }
  }
}
```
Cela pose plusieurs problèmes:  
  1- Les éléments des stats sont des attributs et non sous forme de tableau, donc il faut connaitre le nom des équipes pour pouvoir parser les stats !
  2- C'est le nom de l'équipe qui est utilisé ce qui n'est pas un identifiant stable contrairement à un ID

Voici ma proposition:
```json
[
    {
      "CodeEquipe": "VCVX6",
      "Matchs": 14,
      "MatchsJoues": 12,
      "MatchsDomicile": 6,
      ...
    },
    {
      "CodeEquipe": "VCVX1",
      "Matchs": 8,
      "MatchsJoues": 9,
      "MatchsDomicile": 5,
      ...
    }
]
```
=> Un tableau de stats (un élément par équipe) avec le code équipe. La 1ère partie renvoyé actuellement (les infos Club) sont redondantes car déjà récupéré par de multiple endpoint existant.

**Comment by Lo0ping** [comment]
fait

**Comment by eric-taix-teads** [comment]
Nice merci 👍
