### ISSUE TITLE
Issue in navigation when a team is in several championships

### ISSUE THREAD

**Issue by clapoujade** [eric-taix/volley34-mobile#263]
Step to reproduce:
1/ Display the VLM/4 détails in challenge 6*6 
mixte poule 2 => in the ranking, there is 4 teams.
2/ click on SGVB / 1 Mixte in order to display its détails.

=> The SGVB team details are displayed BUT in the wrong championship: 'Championnat' instead of 'Challenge'; with 6 teams. This issue can happens when a team is in several championships. Obviously, the user can click the accurate championship tab to fix it, but it is a bit disturbing in the navigation worklflow.

When displaying team details, the championship context should be a parameter of the navigation in order to display the team details in the correct championship context.

**Comment by eric-taix** [comment]
Very good catch, not easy to find ;-)
