### ISSUE TITLE
Missing information for "Lunel Volley Ball" team

### ISSUE THREAD

**Issue by clapoujade** [eric-taix/volley34-mobile#264]
In championship 'Challenge, excellence, 6*6 mixte'
Teams details seems properly displayed.
This is true for all teams but one: "Lunel Volley Ball"
For this given team, on january 15th:
- We can see that the team won 3-1 againt "VBSMT / Team Brocante" (through the VBSMT result page).
- The given match appears in the agenda page (while it should be displayed in the result page.
- In the statistics, most of them but two are properly fed: 'Diff de sets' and 'Forces'

**Comment by eric-taix** [comment]
Strange behavior here!

This pool has 4 teams.
<img width="339" alt="Capture d’écran 2022-01-15 à 15 35 22" src="https://user-images.githubusercontent.com/712517/149625584-c6d1aa87-46c2-414b-8d9c-5dd5a7d000a8.png">

When I request all competitions a team is registered to with `Lunel VolleyBall` (team's code `LUNELVBX2 `) with `http://api.volley34.fr/v1/equipes/{{Equipe}}/competitions` the response is:
```
[
    {
        "CompetitionCode": "2022-C055",
        "Saison": 2022,
        "Niveau": "LO",
        "TrancheAge": "SE",
        "RegroupementSexe": "X",
        "TypedeJeu": "6x6",
        "TypeCompetition": "T1        ",
        "LibelleCompetition": "Challenge 6x6 Mixte",
        "DateDebut": "2022-05-04T00:00:00",
        "DateFin": "2022-06-30T00:00:00",
        "CompetitionGroupID": "C6",
        "Created": null,
        "Modified": null,
        "division": "0",
        "poule": "4",
        "Classements": null
    }
]
```
which is wrong as `Lunel Volley Ball` is registered in pool 3 as mentioned in the Volley34's web site.

Also when I request the ranking for the same team (i.e. `http://api.volley34.fr/v1/Classements/equipes/{{Equipe}}`) the response is:
```
        "ClassementCode": "2022-C055-EX-3",
        "Libelle": "Challenge 6x6 Mixte - 2022",
        "CompetitionCode": "2022-C055",
        "Division": "EX",
        "Poule": "3",
        "Personnalise": false,
        "Promus": 2,
        "Relegue": 2,
        "Saison": 2022,
        "Created": null,
        "Modified": null,
```
which is ok for the pool!

And finally the team's name is not the same depending on the end point (for `SMDTX1`):
Ranking's endpoint `http://api.volley34.fr/v1/Classements/equipes/{{Equipe}}` returns `SMDT/Team Brocante` but if I retrieve team's informations from `http://api.volley34.fr/v1/equipes/{{Equipe}}` endpoint, it returns `VBSMT/Team Brocante`.

Well I'm a bit lost. 
@Lo0ping Could you help me to figure out what's happening here? What's right, what's wrong, did I miss something?

**Comment by Lo0ping** [comment]
Salut, 
cela semble provenir d'un problème de données, j'ai fait les corrections nécessaires, est ce que c'est mieux ?
- Lunel est en poule 3
- SMDT/Team Brocante => VBSMT/Team Brocante
- SMDT/Team Savoyarde => VBSMT/Team Savoyarde

**Comment by clapoujade** [comment]
Fixed 👍.

**Comment by eric-taix** [comment]
👍 
Juste pour savoir, il y a eu un problème qui ressemblait à ça remonté par Christophe Seck (SGBV/1 Mixte contre VLCA/ A Sec) où à un moment dans le détail d'une équipe on voyait le résultat du match mais dans le détail d'une autre on ne le voyait pas. Et samedi cela c'est résolu (tout seul). Est ce que c'était aussi un problème de données que tu as corrigé ?
