### ISSUE TITLE
Verify force computations

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#265]
Verify forces computations for several teams:
- verify for a team which has at least 2 competitions
- verify for a team which has no result
- verify for teams in different competitions

**Comment by clapoujade** [comment]
Not easy to check....but in excellence poule 3, the teams Avgm3 and Asc2m have defense force very low, which is weird

**Comment by eric-taix** [comment]
I checked with Excel but not easy as an error, while typing a result, has a real impact on all teams in the same competition. But with 3 teams, things seem better than ever :-D
