### ISSUE TITLE
divisions are displayed in bad order

### ISSUE THREAD

**Issue by clapoujade** [eric-taix/volley34-mobile#266]
In the 'championnat' page, divisions are displayed in alphabetical or random order (while it should be from Excellence down to Loisirs).
This is true for 4*4 mixte.

**Comment by eric-taix** [comment]
Would you mean competition page? Can you provide a screenshot please or at least what did you expect?

Is it related to the fact that divisions names do not reflect "brassage" or not "brassage"?

**Comment by clapoujade** [comment]
Yes I meant 'competitions', sorry.
Screenshot is not possible, but if you filter against 'championnat 4*4 mixte', the order is the following:
- Ascension
- Excellence
- Honneur
- Loisirs 1
- 'blank'
- Promotion.
Not really an alphabetical order (as there is 'blank' in the middle), but not an user friendly order anyway.
