### ISSUE TITLE
Sending result - view from dashboard

### ISSUE THREAD

**Issue by matt-aubert** [eric-taix/volley34-mobile#270]
When you play a game, the next day it disappears from the dashboard which makes the only option to send the result through "agenda".
It's been escalated by a user that it would be more user friendly to either : 

1- Leave any game with no result in the dashboard
or
2- Allow a scroll in the past for dashboard as it currently is for "agenda"

Let see what can be done here.
Personally, I would go for the first option, it is interesting after a game that this card would change its role into a visual "reminder" to send result for both teams.

**Comment by eric-taix** [comment]
Good idea 👍

I kept the matches which have a date before today AND which do not have a result. To add a visual reminder I added a warning icon at the top left of the card. Also I do not scroll the list to the first match in the future: all past matches with no result will be visible.

<img width="338" alt="Capture d’écran 2022-01-26 à 11 45 12" src="https://user-images.githubusercontent.com/712517/151149677-2bfcd4c9-bf68-413b-a75c-ff2281ef6036.png">

As I need to load the full agenda of the team, the "Load more events" has been removed.
