### ISSUE TITLE
Team's competitions do not return all competition

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#276]
When I use the ranking endpoint (`http://api.volley34.fr/v1/Classements/equipes/{{Equipe}}`) for `VCVX1`, 2 competitions are returned: `2022-C004` and `2022-C024`.

But when I use the team's competitions endpoint (`http://api.volley34.fr/v1/equipes/{{Equipe}}/competitions`) then only one competition is returned:
```
[
    {
        "CompetitionCode": "2022-C004",
        "Saison": 2022,
        "Niveau": "LO",
        "TrancheAge": "SE",
        "RegroupementSexe": "X",
        "TypedeJeu": "4x4",
        "TypeCompetition": "T1        ",
        "LibelleCompetition": "Championnat 2022 (Brassage) - Mixte 4x4",
        "DateDebut": "2021-11-08T00:00:00",
        "DateFin": "2022-01-14T00:00:00",
        "CompetitionGroupID": "CH",
        "Created": null,
        "Modified": null,
        "division": "1",
        "poule": "2",
        "Classements": null
    }
]
```

It seems to be a regression as it worked few days ago. The impact is that now I'm not more able to display all competitions in club's teams tab:
<img width="327" alt="Capture d’écran 2022-01-26 à 12 53 51" src="https://user-images.githubusercontent.com/712517/151158741-dff53947-a8d2-4fc7-b8e6-0fc8f7cfc244.png">

**Comment by eric-taix** [comment]
En y repensant ce n'est peut être pas une régression car auparavant je n'utilisais pas le endpoint `http://api.volley34.fr/v1/equipes/{{Equipe}}/competitions` mais celui retournant les classements d'une équipe (j'ai effectué le changement pour avoir les numéros de divisions correctes et non pas les `EX`)

**Comment by eric-taix** [comment]
@Lo0ping tu as vu cette issue ? Elle est assez bloquante car sans elle je ne peux remonter correctement les informations des compétitions en cours pour chaque équipe.

**Comment by Lo0ping** [comment]
OK, je regarde ça rapidement

**Comment by Lo0ping** [comment]
Franchement, 
faut que je debuggue en détail car la, je ne vois vraiment pas ce qui cloche 

![image](https://user-images.githubusercontent.com/3205330/151379184-b786c433-722a-4409-a974-ca92e4224d81.png)

**Comment by Lo0ping** [comment]
C'est bon, j'ai trouvé ...
les inscriptions ne sont reliées qu'a la poule de brassage 😒😒😒
ça va être la m... a modifier ça !!!

**Comment by eric-taix** [comment]
Bon ce n'est peut être pas à faire maintenant du coup ! Maintenant j'avais besoin de ce endpoint parce que pour certaines équipes le fait de relier le division `EX` à la division 1 ne marche pas toujours ! (Cf une autre issue la dessus). Si tu arrives à résoudre le fait que `EX` est relié à 1 (et idem pour les autres divisions) alors je pourrais à priori utiliser le endpoint de classement d'une équipe pour connaître les compétitions auxquels l'équipe est inscrite.

**Comment by Lo0ping** [comment]
Le truc, c'est que tu auras le même problème avec la coupe.
Faut que je vois cette histoire de niveau, ça fout trop le bordel

**Comment by Lo0ping** [comment]
Hello, 
ça devrait être bon ... 
```
[
    {
        "CompetitionCode": "2022-C001",
        "Saison": 2022,
        "Niveau": "LO",
        "TrancheAge": "SE",
        "RegroupementSexe": "M",
        "TypedeJeu": "4x4",
        "TypeCompetition": "T1        ",
        "LibelleCompetition": "Championnat 2022 (Brassage) - Masculin 4x4",
        "DateDebut": "2021-11-08T00:00:00",
        "DateFin": "2022-01-14T00:00:00",
        "DateLimiteReport": null,
        "CompetitionGroupID": "CH",
        "Created": null,
        "Modified": null,
        "division": "EX",
        "poule": "1",
        "Classements": null
    },
    {
        "CompetitionCode": "2022-C021",
        "Saison": 2022,
        "Niveau": "LO",
        "TrancheAge": "SE",
        "RegroupementSexe": "M",
        "TypedeJeu": "4x4",
        "TypeCompetition": "T1        ",
        "LibelleCompetition": "Championnat 2022 - Masculin 4x4",
        "DateDebut": "2022-01-24T00:00:00",
        "DateFin": "2022-04-01T00:00:00",
        "DateLimiteReport": null,
        "CompetitionGroupID": "CH",
        "Created": null,
        "Modified": null,
        "division": "HO",
        "poule": "0",
        "Classements": null
    }
]
```
à vérifier aussi,  tu ne devrais plus avoir de valeur numérique dans Division. si c'est le cas préviens moi.

**Comment by eric-taix** [comment]
Nickel. Je regarde ça ce soir

**Comment by eric-taix** [comment]
Désolé je n'ai pas eu le temps de regarder avant maintenant.

1- `http://api.volley34.fr/v1/equipes/{{Equipe}}/competitions` avec `VCVX1` pour l'équipe retourne
```
[
    {
        "CompetitionCode": "2022-C004",
        "Saison": 2022,
        "Niveau": "LO",
        "TrancheAge": "SE",
        "RegroupementSexe": "X",
        "TypedeJeu": "4x4",
        "TypeCompetition": "T1        ",
        "LibelleCompetition": "Championnat 2022 (Brassage) - Mixte 4x4",
        "DateDebut": "2021-11-08T00:00:00",
        "DateFin": "2022-01-14T00:00:00",
        "CompetitionGroupID": "CH",
        "Created": null,
        "Modified": null,
        "division": "EX",
        "poule": "2",
        "Classements": null
    }
]
```
donc toujours qu'une seule compétition !

Par contre effectivement j'ai bien `EX` comme division. Du coup pour interroger `http://api.volley34.fr/v1/Classements/{{Competition}}/{{Division}}/{{Poule}}` je peux utiliser `EX` comme division ou je dois utiliser la correspondance de la liste des divisions ? 
PS: Cette requête prend 5 secondes à me retourner un résultat, cela me parait énorme non ?

**Comment by eric-taix** [comment]
Assez bizarre, je faisais des tests sur `apitest.volley34.fr` et là j'ai bien 2 compétitions qui me sont retournées pour `VCVX1` : `2022-C004` et `2022-C024` (avec les divisions et poules correspondantes) alors que sur `api.volley34.fr` je n'ai que `2022-C004` ? 
Les corrections que tu as faites (https://github.com/eric-taix/volley34-mobile/issues/276#issuecomment-1024045838) n'ont pas été faites sur le backup de la base que tu as remontée par hasard mais pas sur la base de prod ?

**Comment by Lo0ping** [comment]
```
Par contre effectivement j'ai bien EX comme division. Du coup pour interroger http://api.volley34.fr/v1/Classements/{{Competition}}/{{Division}}/{{Poule}} je peux utiliser EX comme division ou je dois utiliser la correspondance de la liste des divisions ?
```
Oui, et si tu rencontres une méthode ou il te faut encore mettre '1' à la place de 'EX', previens-moi

```
PS: Cette requête prend 5 secondes à me retourner un résultat, cela me parait énorme non ?
```

j'ai optimisé le chargement, ça devrait aller mieux

```
Assez bizarre, je faisais des tests sur apitest.volley34.fr et là j'ai bien 2 compétitions qui me sont retournées pour VCVX1 : 2022-C004 et 2022-C024 (avec les divisions et poules correspondantes) alors que sur api.volley34.fr je n'ai que 2022-C004 ?
Les corrections que tu as faites (#276 (comment)) n'ont pas été faites sur le backup de la base que tu as remontée par hasard mais pas sur la base de prod ?
```
Bah, c'est surtout que je n'avais pas déployé l'API en prod 😒
ça devrait aller mieux ...

**Comment by eric-taix** [comment]
Ok. @Lo0ping Depuis le déploiement je rencontre une erreur serveur (500) pour:
- `http://api.volley34.fr/v1/equipes/VCVX1/resultats`
- `http://api.volley34.fr/v1/resultats/2022-C004/EX/2`
- `http://api.volley34.fr/v1/Classements/equipes/VCVX1`
Je ne pense pas que le code équipe ou division ou poule change les choses, donc certainement valable quelque soit les paramètre de l'URI

**Comment by Lo0ping** [comment]
C'est bon ... 
j'ai un peu trop optimisé le chargement 😜

**Comment by eric-taix** [comment]
Ok. J'ai maintenant `http://api.volley34.fr/v1/competitions` qui me renvoit `null`, je pense que c'est lié à tes modifications / optimisations ?

**Comment by Lo0ping** [comment]
c'est corrigé, désolé ...
