### ISSUE TITLE
Envoie des resultats et report

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#278]
L'envoi des résultats et report pose un réel soucis dans la gestion des relances. 
en effet, via l'apps, cela n'envoie qu'un mail
via le site, ca envoie un mail + enregistre l'info dans la BDD + génère (et stocke) un fichier xml + stocke la FDM

la gestion des relances est bien évidement connecté a la BDD pour éviter de relancer des équipes qui ont déjà saisi leur score. 
via l'apps, du coup, tel que c'est fait aujourd'hui, ce n'est malheureusement pas possible et entraine une charge de travail supplémentaire.

Il faudrait rapidement envisager d'utiliser l'API, svp

**Comment by eric-taix** [comment]
Oui je confirme. J'avais repoussé l'utilisation de l'API car il y avait déjà un système qui marchait et au vu des soucis que l'on rencontre ces derniers temps je l'avais mis en stand by mais si effectivement cela n'est pas jouable par mail quelque soit la raison je le remets en prioritaire !

**Comment by matt-aubert** [comment]
ok donc je clôture cette issue 
Duplicate of #204
