### ISSUE TITLE
Warning icon not well aligned 

### ISSUE THREAD

**Issue by matt-aubert** [eric-taix/volley34-mobile#286]
![20220204_005006.jpg](https://user-images.githubusercontent.com/95641846/152448660-622e5eff-3750-46f5-a855-91285001176e.jpg)

**Comment by eric-taix** [comment]
Really strange, on my phone the icon is well aligned![Screenshot_20220204-010013.jpg](https://user-images.githubusercontent.com/712517/152494319-00cf9914-1e8d-425c-bb68-fe6c83b0c2a9.jpg)

**Comment by eric-taix** [comment]
Ok understood why ;-) 
This issue is when the forces are not displayed
