### ISSUE TITLE
Game screen loading delays

### ISSUE THREAD

**Issue by matt-aubert** [eric-taix/volley34-mobile#287]
Need to wait 10 sec to load information 

![20220204_004939.jpg](https://user-images.githubusercontent.com/95641846/152448868-e6d64003-8210-405d-a46e-6e2e5689ea2a.jpg)

**Comment by eric-taix** [comment]
@Lo0ping Voici les requêtes et leur temps respectif:
| Requête  | Temps (ms) |
| ------------- | ------------- |
| http://api.volley34.fr/v1/clubs  | 7206 |
| http://api.volley34.fr/v1/clubs/{{club}}/equipes  | 5669 |
| http://api.volley34.fr/v1/equipes/{{equipes}}/resultats | 2316 |
| http://api.volley34.fr/v1/calendars?equipe={{equipe}}&min=2022-02-07T15:00:00&max=2022-06-07T16:00:00 | 2295 |
| http://api.volley34.fr/v1/classements/equipes/{{equipe}} | 5445 |
| http://api.volley34.fr/v1/clubs/{{club}}/stats | 5785 |
| http://api.volley34.fr/v1/classements/equipes/{{equipe}} | 5814 |
| http://api.volley34.fr/v1/clubs/{{club}}/creneaux | 5594 |

J'ai déjà vu des 19 secondes dans mes logs donc ce n'est pas constant à priori. Je rajouterais dans un prochain build un menu experimental permettant de visualiser les requêtes les plus lentes avec leur temps respectif. 

Certains écrans nécessitent plusieurs requêtes. Quand je peux je les parallélisme mais je ne peux pas toujours ce qui fait que le temps d'affichage de ces écrans est la somme de 2 requêtes d'où des temps assez long.

PS: Pour l'instant j'ai fixé un seuil max pour déterminer si une requête est lente à 1000ms ce qui déjà assez long normalement

**Comment by Lo0ping** [comment]
Salut, 

je vais regarder ... 
j'ai l'impression que mon pb vient du fait qu'il réinitialise mon contexte à chaque requête et du coup, il recharge tout et dans des données inutiles.

par exemple pour les entrée de http://api.volley34.fr/v1/clubs/..., il chargeais a chaque fois tous les clubs, toutes les équipes et tous les créneaux ... et equipes est long.

2 options possibles : 

1. - je trouve comment conserver mon contexte
2. - je modifie chaque endpoint pour allez chercher direct en BDD les infos utiles

je vais accorder un peu de temps pour l'option 1 et sinon, j'enverrais sur la 2e

**Comment by eric-taix** [comment]
Tu as déjà travaillé dessus car j'ai l'impression (sans mesure) que les temps de réponse sont bien plus rapide ?

**Comment by Lo0ping** [comment]
J'ai touché a club (ajout d'un index et chargement plus ciblé) mais faut que je trouve d'autre moyens d'optimiser tout ça

**Comment by eric-taix** [comment]
Related to #298. Do we need to keep both?
