### ISSUE TITLE
Afficher le détail d'un club

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#3]
En cliquant sur un club dans la liste des sites, pouvoir afficher le détail du club avec toutes les informations nécessaires sur celui-ci.

**Comment by Lo0ping** [comment]
http://api.volley34.fr/api/clubs/<ID>
ex : http://api.volley34.fr/api/clubs/VCV

**Comment by eric-taix-teads** [comment]
Close, will create more fine grained issues
