### ISSUE TITLE
Manque des infos pour récupérer les compétitions d'une équipe

### ISSUE THREAD

**Issue by eric-taix-teads** [eric-taix/volley34-mobile#31]
**Besoin**
Pouvoir récupérer pour une équipe, les classements par compétitions où l'équipe est inscrite

**Constat**
A moins qu'il y ait un autre endpoint que je n'ai pas vu mais je ne trouve pas l'information de division ni de poule pour une équipe. Le endpoint `http://api.volley34.fr/v1/equipes/{{Equipe}}/competitions`retourne le json suivant:
```json
[
    {
        "CompetitionCode": "2020-C004",
        "Saison": 2020,
        "Niveau": "LO",
        "TrancheAge": "SE",
        "RegroupementSexe": "X",
        "TypedeJeu": "4x4",
        "TypeCompetition": "T2        ",
        "LibelleCompetition": "Championnat 2020 - Mixte 4x4",
        "DateDebut": null,
        "DateFin": null,
        "CompetitionGroupID": "CH",
        "Created": null,
        "Modified": null
    },
    {
        "CompetitionCode": "2020-C104",
        "Saison": 2020,
        "Niveau": "LO",
        "TrancheAge": "SE",
        "RegroupementSexe": "X",
        "TypedeJeu": "4x4",
        "TypeCompetition": "T1        ",
        "LibelleCompetition": "Coupe de Printemps 2020 - Mixte 4x4",
        "DateDebut": null,
        "DateFin": null,
        "CompetitionGroupID": "CO",
        "Created": null,
        "Modified": null
    }
]
```
Or ces informations ne sont pas suffisantes pour ensuite pouvoir appeler `http://api.volley34.fr/v1/Classements/{{Competition}}/{{Division}}/{{Poule}}` car il manque la `division` et la `poule`

Sinon il y a `http://api.volley34.fr/v1/Classements/equipes/{{Equipe}}` qui devrait permettre de récupérer l'ensemble des classements d'une équipe mais les tests montrent que seuls les classements du championnat remontent.

**Comment by eric-taix-teads** [comment]
En fait il y a bien une remontée de toutes les compétitions quand une équipe est engagée dans plusieurs compétitions.

**Comment by Lo0ping** [comment]
pour simplifier, je vais ajouter l'entrée 
http://api.volley34.fr/v1/equipes/{{Equipe}}/Classements
