### ISSUE TITLE
Erreur VLM/Prisma - Coupe de prinptemps

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#316]
Je n'ai pas encore le détail du pourquoi mais le fait que VLM/Prisma soit inscrit au dernier moment dans la coupe de printemps, fait que certaines API ne doivent pas les remonter correctement !

Par exemple, je vois bien dans l'application qu'ils sont sur la coupe de printemps mais quand je demande le classement de leur poule, j'ai toujours OLAP Cap ou pas Cap. Du coup cela provoque des erreurs dans l'application. Je corrige pour que cela ne plante plus mais pour autant je pense que les données ne vont pas s'afficher correctement.

**Comment by Lo0ping** [comment]
Le remplacement manuel de OLAP par prisca a eut quelques effets de bord ... 
normalement c'est bon désormais ...
sa fiche ne plante plus et le classement a été regénéré, donc elle y apparait ...
je te laisse valider et ferme ce bug

**Comment by eric-taix** [comment]
Merci @Lo0ping  nickel ca fonctionne 👍
