### ISSUE TITLE
Résultats de la coupe de printemps

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#317]
Quand je demande les compétitions pour l'équipe VCVX1 via `http://api.volley34.fr/v1/equipes/{{Equipe}}/competitions` la réponse est
```
        "Classements": null
    },
    {
        "CompetitionCode": "2022-C104",
        "Saison": 2022,
        "Niveau": "LO",
        "TrancheAge": "SE",
        "RegroupementSexe": "X",
        "TypedeJeu": "4x4",
        "TypeCompetition": "T1        ",
        "LibelleCompetition": "Coupe Robert Potier 2022 - Mixte 4x4",
        "DateDebutInscription": null,
        "DateFinInscription": null,
        "DateDebut": "2022-05-04T00:00:00",
        "DateFin": "2022-06-21T00:00:00",
        "DateLimiteReport": null,
        "CompetitionGroupID": "CO",
        "Created": null,
        "Modified": null,
        "division": "0",
        "poule": "3",
        "Classements": null
    }
```
Du coup j'interroge les résultats par le endpoint suivent `http://api.volley34.fr/v1/resultats/{{Competition}}/{{Division}}/{{Poule}}` en utilisant respectivement `2022-C104` , `0` et `3` pour la competition, la division et la poule. La réponse est vide !

Note: Pour autant le endpoint `http://api.volley34.fr/v1/Classements/{{Competition}}/{{Division}}/{{Poule}}` avec les mêmes valeurs de paramètres retourne les résultats attendus: d'où d'ailleurs le fait que le classement soit bien affiché dans l'application mobile.

**Comment by Lo0ping** [comment]
Problème de gestion des poules et niveaux.
C'est réglé normalement
