### ISSUE TITLE
[dashboard] Change the loader when the current team classification are currently being retreived

### ISSUE THREAD

**Issue by eric-taix-teads** [eric-taix/volley34-mobile#33]
On the dashboard when a team card is shown, the current classifications are retrieved from the server. There's no Ui indication that the loading operation is currently processing

**Comment by thomasFoulon** [comment]
The loader have been implemented in the closed issue #34, but I don't think this type of loader is the best for a team card. What do you think we should use ? I have thought about the `ThreeBounce` indicator of the [flutter_spinkit](https://pub.dev/packages/flutter_spinkit) package.

**Comment by thomasFoulon** [comment]
No `ThreeBounce` just for `TeamCard` not others, I think `ChasingDots` is very well for other cards !
