### ISSUE TITLE
[dashboard] Use BouncingScrollPhysics for club pageview

### ISSUE THREAD

**Issue by eric-taix-teads** [eric-taix/volley34-mobile#35]
In the dashboard, the pageview for the club cards use the default (platform) physics. As we used the `BouncingScrollPhysics` physic for the team cards, we should use the same physic for all pageview / listview / ...

**Comment by thomasFoulon** [comment]
When I apply `physics: const BouncingScrollPhysics()` in the `PageView.builder()` for the club cards, there is no animation. I don't know where the problem can be. Functions of `BouncingScrollPhysics` are called.
