### ISSUE TITLE
Endpoint pour la liste des gymnases

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#4]

**Comment by Lo0ping** [comment]
Fournir un endpoint pour la liste des Gymnases avec toutes les informations de chaque gymnase

**Comment by eric-taix-teads** [comment]
Est-il possible d'avoir pour chaque gymnase le `codeClub`? L'idée est de pouvoir cliquer sur un gymnase pour avoir les coordonnées du club.
Question: est-il possible qu'un gymnase soit partagé (à des horaires différents) par plusieurs clubs ?

**Comment by Lo0ping** [comment]
> Est-il possible d'avoir pour chaque gymnase le codeClub? L'idée est de pouvoir cliquer sur un gymnase pour avoir les coordonnées du club.

Ce sont les inscriptions aux compétitions qui permettent de donner cette info

> Question: est-il possible qu'un gymnase soit partagé (à des horaires différents) par plusieurs clubs ?

 Oui, par exemple : Sanofi et Agropolis Cabelas se partage le gymnase de Rimbaud le jeudi
Mais je crois que ce sont les seuls

**Comment by Lo0ping** [comment]
http://api.volley34.fr/v1/Gymnases
