### ISSUE TITLE
[dashboard] FavoriteClubCards and team Cards haven't the same scroll physics

### ISSUE THREAD

**Issue by thomasFoulon** [eric-taix/volley34-mobile#43]
On the dashboard, club and team cards have not the same scroll physics. Indeed a `BouncingScrollPhysics` is attached to the PageView of team cards (see `dashboard_club_teams.dart`). Is this a problem is terms of consistent UI ?

**Comment by thomasFoulon** [comment]
I didn't see the issue #35. I close this issue.

**Comment by eric-taix-teads** [comment]
I think it's better to have a consistent UI. No?
