### ISSUE TITLE
[common] Define the color of the card's title background in a specific ThemeData

### ISSUE THREAD

**Issue by thomasFoulon** [eric-taix/volley34-mobile#44]
The color of the card's title background is hard coded (`lighten(3)`) at several places in the code. We should instead define a specific `ThemeData` to provide a specific style.

**Comment by thomasFoulon** [comment]
After some researches it seems that we have two ways of doing it. Either an `extension` of `ColorScheme` or we can also extend the `CardTheme` with a new field for the card's title background color.

What do you think is the best in our case ?

**Comment by eric-taix** [comment]
I think extending `CardTheme` is a better idea: we'll probably reuse this
solution for other specific styles we may use in the future. And by the
way, I wanted to implement another theme (a light one), so the user can
switch to each other.

Or it can be switched automatically depending on the current time: it's
better to have a black theme during the night (for eyes) and much better to
use a light theme during the day especially when the sun rises ;-)

Can't remember if I've created issues for these ideas...

Le jeu. 25 juin 2020 à 15:45, thomasFoulon <notifications@github.com> a
écrit :

**Comment by thomasFoulon** [comment]
I don't see any issue about black and white themes. I create it !
