### ISSUE TITLE
[theme] Add a way for the user to switch between a 'light' and a 'dark' theme

### ISSUE THREAD

**Issue by thomasFoulon** [eric-taix/volley34-mobile#47]
As @eric-taix proposed in https://github.com/eric-taix/volley34-mobile/issues/44#issuecomment-649588927, it would be nice to let the user choose between two themes (dark and light).

Where do you think the option should appear ?

**Comment by eric-taix** [comment]
Well good question. I thought about reworking the main pages (dashboard, competitions and clubs) and add an App bar with the title of the selected page and an icon to display the preference page. Wdyt ?

**Comment by thomasFoulon** [comment]
I'm not really sure an App bar could render well (more precisely the Android app bar). I've thought about a simple icon in the top right to open the preference page if there will be more than the theme preference. If the theme is the only preference, just a button to switch between the two themes could be sufficient !
