### ISSUE TITLE
[dashboard] Find a way to well show to the user that there is an agenda

### ISSUE THREAD

**Issue by thomasFoulon** [eric-taix/volley34-mobile#48]
On my phone screen, the graphical elements we added lowered the agenda part of the dashboard (see the screenshot). I think some small screen users could not be aware of the fact that there is an agenda part on the dashboard if they don't scroll vertically.

Do you think there is a way to show the user the fact that this part of the dashboard exists ?

<img src="https://user-images.githubusercontent.com/67117547/85850809-d3459780-b7ad-11ea-9d8f-14c7a9b20e35.jpg" height="400px">

**Comment by eric-taix** [comment]
First note that this issue can be seen with different mobile size.
I think we can fix it with different solution:
1- add a floating button to the bottom right of the screen, with a down
arrow to indicate that there's more to see. If the user click then we
scroll to the section (the agenda)
2- the bottom bar disappear after a fixed duration which reveal the start
of the agenda. If the user scroll up or down then the bottom bar should
appear (this pattern should be applied to all views in the main page:
dashboard, competitions, clubs)

My preference goes to the second one

Le ven. 26 juin 2020 à 13:11, thomasFoulon <notifications@github.com> a
écrit :

**Comment by Lo0ping** [comment]
Hi, 
first of all, please reduce unuseful spaces between components (in yellow in screenshot)
![image](https://user-images.githubusercontent.com/3205330/85857749-bc597200-b7ba-11ea-8c7b-0d868498c93f.png)

**Comment by Lo0ping** [comment]
And ok for solution 2

**Comment by thomasFoulon** [comment]
I agree with @Lo0ping about the fact that we could reduce spaces between the elements. The solution 2 has my preference too but I don't know if a lot of well known applications are doing that way. I mean, it could loose the user because he's not used to disappearance. What do you think ?

**Comment by eric-taix** [comment]
Yes we can reduce the space but not too much: space has a semantic meaning
in UI (it separates different parts and is different from small space
between tiles for example).
Also reducing space won't solve the issue which may appear even with small
spaces regarding the size of the phone).
I agree Thomas that this pattern may not be the good one and that it don't
follow a well known pattern. But let's give it a try no ? But before just
reduce the size of the space as suggested by Laurent (but not too much) and
let's see...

Le ven. 26 juin 2020 à 16:18, thomasFoulon <notifications@github.com> a
écrit :
