### ISSUE TITLE
[Dashboard] - Team Order and visibility

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#49]
Hi ! 
in th dashboard : 
![image](https://user-images.githubusercontent.com/3205330/85858137-6a651c00-b7bb-11ea-9bb0-37a3e5795304.png)
Teams are not ordered by name or competitions or ranking or TeamCode.
could you change it to order the list by Team name ?

Also, don't forget to able users to select teams he want to see on dashboard

**Comment by thomasFoulon** [comment]
> Also, don't forget to able users to select teams he want to see on dashboard

Hi ! What do you think about a favorite icon on the card ? Do we let him select them on the dashboard or on an another view ?

**Comment by eric-taix** [comment]
We have to check but I think that team are ordered by team code.
First I thought about adding a favorite feature for team too but not sure
this is relevant

Le ven. 26 juin 2020 à 16:26, thomasFoulon <notifications@github.com> a
écrit :

**Comment by Lo0ping** [comment]
> We have to check but I think that team are ordered by team code.
> 

Sure not with my teams.
as3mt/Beach should be first by name and team code (AS3MT2)
