### ISSUE TITLE
[dashboard] Selected favorite club card and selected team card are not memorized when scrolling down

### ISSUE THREAD

**Issue by thomasFoulon** [eric-taix/volley34-mobile#54]
When the user is scrolling down on the dashboard, current pages of club and team cards are not memorized. The consequence is that when the user returns to the cards by scrolling up, he sees the first club when he was for example on the third club before. He's also seeing the first team of the third club which is the most important problem.

I did some research about the subject and I found the `AutomaticKeepAliveClientMixin` class we could use. It applies to the states we want to be "memorized" when the linked widget is not shown on the screen. In our case we could apply it to the cards. I tried it and it works but the performances (60 fps) are quite lowered.

Do you know a solution cleaner and with no performance problem ?

**Comment by thomasFoulon** [comment]
I've found another solution maybe more adapted to our case : `PageStorageKey`. I tested it but the performances are lowered as well.

**Comment by eric-taix-teads** [comment]
Did you run the application in `profile` mode to verify the performance? This is a requirement: you can't verify the performance in `debug` mode. To launch the application in `profile` mode click on this button in IntelliJ
<img width="31" alt="Capture d’écran 2020-06-30 à 13 38 03" src="https://user-images.githubusercontent.com/42940156/86121808-fab2a200-bad6-11ea-8c92-64abc81b59ea.png">

**Comment by eric-taix-teads** [comment]
With `AutomaticKeepAliveMixin` did you call `super.build(context)` in the `build` method?
I can't see why adding this mixin would decrease the performance....

**Comment by thomasFoulon** [comment]
Yes I ran the application in `profile` mode. I forgot to call `super.build(context)`, that's maybe why !

**Comment by eric-taix** [comment]
Any news from the performance when calling `super.build` ? Did it solve the performance issue ?
