### ISSUE TITLE
[dashboard] Club PageView UX/UI must be consistent with Team PageView

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#56]
To be consistent, the club PageView controller must use the same `viewportFraction: 0.8` and same margin/padding

**Comment by thomasFoulon** [comment]
So we reduce the size of the club PageView ? I think it would be better to increase the size of the team PageView ! What do you think ?

**Comment by eric-taix** [comment]
Yes try to increase the size of the team cards and let's see

Le jeu. 2 juil. 2020 à 14:58, thomasFoulon <notifications@github.com> a
écrit :

**Comment by thomasFoulon** [comment]
I've tried to modify several elements but it's quite tricky to increase the width of team cards. Do you have an idea of the attribute we should modify ?
