### ISSUE TITLE
[dashboard] Team as favorite

### ISSUE THREAD

**Issue by eric-taix-teads** [eric-taix/volley34-mobile#60]
It can be tricky to swipe all teams (especially for club which has a lot of teams) to display your favorite(s) one(s).
Now teams are sorted by their name, but favorite's teams must be displayed first.

   

- [x] Add the ability to set one or more teams as favorite (in the club page)
- [x] Store this favorite teams in the local storage as we've done for club (with a different key per club?). 
- [x] In the dashboard, display first all favorite teams and then other teams (but keep alphabetic order in each group)
- [x] Apply the same sort in the club page

**Comment by thomasFoulon** [comment]
Do we use `SharedPreferences` or the `LocalStorage` as for clubs ?
