### ISSUE TITLE
[API] Matchs d'un club

### ISSUE THREAD

**Issue by thomasFoulon** [eric-taix/volley34-mobile#68]

**Comment by thomasFoulon** [comment]
J'aurais besoin de récupérer les matchs d'un club (avec toujours les conditions de date min et max), pour l'agenda sur le dashboard. Est-ce que c'est possible ?

**Comment by eric-taix-teads** [comment]
Il faudrait donc pouvoir récupérer en une seule requête:
  - les matchs d'un club (les matchs dans le futur)
  - les tournois
  - les réunions
  - les résultats d'un club (les matchs joués)
Et comprise entre 2 dates. Le but est de pouvoir ne faire qu'une seule requête pour récupérer l'agenda d'un club (ainsi que d'autres données mais qui sont issues des matchs). Actuellement plusieurs requêtes sont exécutées ce qui n'est pas terrible et ralenti l'application

**Comment by thomasFoulon** [comment]
Est-ce toujours d'actualité par rapport à ce que l'on a convenu hier ? Le contenu du calendrier concernera l'équipe seulement.

**Comment by eric-taix-teads** [comment]
Plus nécessaire pour l'instant
