### ISSUE TITLE
[API] Type de compétition sur un match

### ISSUE THREAD

**Issue by thomasFoulon** [eric-taix/volley34-mobile#75]
J'aurais besoin rapidement de connaître le type de compétition d'un match (championnat, challenge, coupe). En fait je récupère actuellement les résultats d'une équipe, dans un "objet" de type Résultat, j'ai bien un "objet" de type "Match" mais je n'ai que le code de la compétition et pas son nom/type. C'est possible de rajouter ça ?

Un exemple : http://api.volley34.fr/v1/equipes/CVBF2/resultats

**Comment by Lo0ping** [comment]
Thomas, je peux rajouter les infos, mais ça va alourdir les données pour "rien" à mon sens.
La code compétition te donne les informations souhaitées: 

![image](https://user-images.githubusercontent.com/3205330/87853779-700ed700-c90d-11ea-9ee1-7be8c641584c.png)

**Comment by thomasFoulon** [comment]
Merci !

**Comment by Lo0ping** [comment]
petite correction
- coupe (consolantes) : c'est 12 et non 11
