### ISSUE TITLE
[API] Récupération du logo d'un club ou d'une équipe

### ISSUE THREAD

**Issue by thomasFoulon** [eric-taix/volley34-mobile#78]
Bonjour, j'aurais besoin de récupérer le logo d'un club et par extension d'une équipe directement à partir de l'API (pas l'adresse mais l'image au format png).

Par exemple avec : 

`http://<api-volley34>/api/v1/logo/club/<code-club>`
`http://<api-volley34>/api/v1/logo/equipe/<code-equipe>`

Ce serait possible ? Merci d'avance !

**Comment by Lo0ping** [comment]
c'est livré :
http://<api-volley34>/api/v1/clubs/<code-club>/logo
http://<api-volley34>/api/v1/equipes/<code-equipe>/logo

**Comment by thomasFoulon** [comment]
Merci !
