### ISSUE TITLE
[question] Incertitude for the agenda on the dashboard

### ISSUE THREAD

**Issue by thomasFoulon** [eric-taix/volley34-mobile#80]
As @eric-taix-teads noted here https://github.com/eric-taix/volley34-mobile/pull/79#issuecomment-662969588, we don't know if the agenda on the dashboard has to reflect all favorite teams or just a team alone.

**Comment by Lo0ping** [comment]
On the dashboard, we must see all items of all favorites teams (for matchs) et club (for private events)
