### ISSUE TITLE
[API] Limitation des matchs récupérés à un intervalle de dates

### ISSUE THREAD

**Issue by thomasFoulon** [eric-taix/volley34-mobile#83]
J'aurais besoin de récupérer les prochains matchs d'une équipe (sur un mois dans mon cas) pour les afficher sur l'agenda.

http://api.volley34.fr/v1/equipes/{{equipe}}/matchs existe mais serait-il possible de rajouter des paramètres min et max pour la date ?

**Comment by Lo0ping** [comment]
http://api.volley34.fr/v1/equipes/{{Equipe}}/matchs?filter=weeks&value=**4**
limitation sur **4** semaines (incluant la semaine courante)
