### ISSUE TITLE
Mise en place de la saison 2021

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#84]
la BDD de test est a jour et le site www.test.volley34.fr a été mis en ligne

**Comment by Lo0ping** [comment]
@thomasFoulon , @eric-taix  pour infos

**Comment by eric-taix** [comment]
Top on va pouvoir comparer ce que l'on affiche avec la réalité

**Comment by Lo0ping** [comment]
pour la saison 2020-2021, faut que je vois encore comment intégrer les classements et  résultats
