### ISSUE TITLE
Season has switched: no more data

### ISSUE THREAD

**Issue by eric-taix-teads** [eric-taix/volley34-mobile#87]
The next season (2020-2021) is up and running, so there's no more data available.
What can be done? Without data it will be very difficult to continue developing the application.

cc @thomasFoulon : Clubs & Gymnasiums still working, so you can continue to develop the gymnasium map

**Comment by Lo0ping** [comment]
is it better ?
normally, only rankings and results was missing 
now all is up to date

**Comment by eric-taix** [comment]
Yes it's fine thanks

**Comment by eric-taix** [comment]
Even if I missed something but it seems that there's no match! I know it's difficult to have a secondary dataset but without data it becomes difficult to develop and verify features

**Comment by Lo0ping** [comment]
You miss nothing; calendar if up to date for a regular season (from november to june).
I will change dates to start 1st match this week.
but don't forget that you will have matchs in the future with result

**Comment by Lo0ping** [comment]
Done,
