### ISSUE TITLE
relegation Error

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#88]
My Team (as3mt/Beach) was 8th on 10 teams but it is tagged as relegated team that is wrong

Rules : 
for each level of **X** teams
- Teams ranked 1 or 2 are promoted or winner 
- Teams ranked X or X-1 are relegated

**Comment by eric-taix** [comment]
Just a question: the number of promoted / related is returned in the
classification result no? Even if it's almost 2

**Comment by Lo0ping** [comment]
Promotion and relégation is not include in the API (if it's your question)
