### ISSUE TITLE
opponent logo missing in team result

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#95]
event if it's local or visitor, opponent logo is missing in team result page.

ex : 
In as3mt/Beach page, in the first result page, SGVB/2 logo is missing and as3mt/Beach is visible
but in SGVB/2 page, for the same match, as3mt/Beach logo is missing and SGVB/2 logo is visible

**Comment by eric-taix-teads** [comment]
Now the UI of match results has changed. Do we still need to display the logo of the club for each opponent? Or is it now irrelevant?

**Comment by Lo0ping** [comment]
It could be sexiest 😉, but if it's too boring, let it as you commit

**Comment by eric-taix-teads** [comment]
No it's not boring, just a question to know if it's ok now (with the new UI) to add a logo for both team or leave it as it (without any logo). But the logo can be easily added on the top left corner for the visitor and bottom right corner for the opponent
![Simulator Screen Shot - iPhone 11 - 2020-08-18 at 16 16 49](https://user-images.githubusercontent.com/42940156/90524338-3d573900-e16e-11ea-8447-ec6ebbfb8f3d.png)

**Comment by Lo0ping** [comment]
Can you make me a mock up with logos ?

**Comment by eric-taix-teads** [comment]
Sorry the logo background color is not the same as the card background and the logos are not the good one for these teams, but the idea is here! While looking at this mockup, I'm wondering if there are not too much information with the logos (you can click on the image to see it with a normal size")?
![mockup](https://user-images.githubusercontent.com/42940156/90533314-9c21b000-e178-11ea-9582-215c23c3a935.png)

**Comment by Lo0ping** [comment]
That's why I wanted this mock up.
Too much informations kill thé information. 😜
Don't add logos
