### ISSUE TITLE
Flutter icon

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#99]
Sometime flutter icon appear on the shortcut instead of volley34 icon. ![Screenshot_20200813-110837-01.jpeg](https://user-images.githubusercontent.com/3205330/90117459-3d62cd80-dd57-11ea-8c04-02de359b425f.jpeg)

**Comment by eric-taix-teads** [comment]
Hummm, quite surprising. Does it means that the build process creates (sometimes) some flaky binaries?

**Comment by Lo0ping** [comment]
Or a cache side effect from the first versions
